<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'||!in_array('--allow-local-fixtures',$argv,true))exit("Usage: php tests/phase7.php --allow-local-fixtures\n");
require dirname(__DIR__).'/includes/bootstrap.php';require_once dirname(__DIR__).'/includes/reports.php';require_once dirname(__DIR__).'/includes/report-export.php';
if($config['environment']!=='development')throw new RuntimeException('Development fixtures only.');
$pdo=db();$base=rtrim((string)$config['test_base_url'],'/');$checks=0;$ids=['users'=>[],'sites'=>[],'traps'=>[],'devices'=>[],'assignments'=>[],'readings'=>[],'alerts'=>[],'surrenders'=>[],'rules'=>[],'incentives'=>[],'ledger'=>[],'audit'=>[]];$emails=[];$testStart=gmdate('Y-m-d H:i:s');
function p7_check(bool $ok,string $label):void{global$checks;if(!$ok)throw new RuntimeException('FAIL: '.$label);$checks++;echo 'PASS: '.$label.PHP_EOL;}
function p7_expect(string $class,callable $work,string $label):void{try{$work();p7_check(false,$label);}catch(Throwable$e){p7_check($e instanceof $class,$label);}}
function p7_http(?CurlHandle $c,string $url):array{$own=$c===null;if($own){$c=curl_init();curl_setopt($c,CURLOPT_COOKIEFILE,'');}curl_setopt_array($c,[CURLOPT_URL=>$url,CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_POST=>false,CURLOPT_CUSTOMREQUEST=>'GET']);$raw=curl_exec($c);$size=curl_getinfo($c,CURLINFO_HEADER_SIZE);$result=['status'=>curl_getinfo($c,CURLINFO_RESPONSE_CODE),'headers'=>substr((string)$raw,0,$size),'body'=>substr((string)$raw,$size)];if($own)curl_close($c);return$result;}
function p7_login(string $base,string $email,string $password):CurlHandle{$c=curl_init();curl_setopt_array($c,[CURLOPT_URL=>$base.'/public/login.php',CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_COOKIEFILE=>'',CURLOPT_FOLLOWLOCATION=>false]);$raw=curl_exec($c);$size=curl_getinfo($c,CURLINFO_HEADER_SIZE);preg_match('/name="csrf_token" value="([a-f0-9]{64})"/',substr((string)$raw,$size),$m);curl_setopt_array($c,[CURLOPT_URL=>$base.'/public/login.php',CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query(['csrf_token'=>$m[1]??'','email'=>$email,'password'=>$password])]);curl_exec($c);return$c;}
try{
 p7_check(APP_VERSION==='0.9.0','Application version is 0.9.0');
 $index=$pdo->query("SHOW INDEX FROM audit_logs WHERE Key_name='idx_audit_created_at'")->fetch();p7_check((bool)$index,'Phase 7 audit date index is applied');
 $period=phase7_report_period(['period'=>'week']);p7_check(str_contains($period['label'],'Monday-Sunday'),'Weekly boundary is documented as Monday-Sunday');
 p7_expect(Phase7ReportValidationException::class,fn()=>phase7_report_period(['period'=>'custom','from'=>'2026-10-02','to'=>'2026-10-01']),'Inverted custom date range is rejected');
 p7_expect(Phase7ReportValidationException::class,fn()=>phase7_report_period(['period'=>'custom','from'=>'not-a-date','to'=>'2026-10-01']),'Malformed date is rejected');
 p7_expect(Phase7ReportValidationException::class,fn()=>phase7_report_period(['period'=>'custom','from'=>'2020-01-01','to'=>'2026-10-01']),'Extreme date range is rejected');
 $safe=phase7_report_filters(['report'=>'telemetry','period'=>'today','sort'=>'id;DROP TABLE users','page_size'=>999]);p7_check($safe['sort']==='newest'&&$safe['page_size']===25,'Sort and page size use safe whitelists');
 p7_expect(Phase7ReportValidationException::class,fn()=>phase7_report_filters(['report'=>'telemetry','period'=>'today','establishment_id'=>'1 OR 1=1']),'SQL-like numeric filter is rejected');
 p7_check(phase7_csv_cell('=2+2')==="'=2+2"&&phase7_csv_cell('+cmd')==="'+cmd"&&phase7_csv_cell('@SUM(A1)')==="'@SUM(A1)",'CSV formula prefixes are neutralized');
 p7_check(phase7_csv_cell("a,b\n\"c\"")==="a,b\n\"c\"",'CSV content is preserved for standards-based fputcsv escaping');
 $roles=$pdo->query('SELECT slug,id FROM roles')->fetchAll(PDO::FETCH_KEY_PAIR);$password='P7!'.bin2hex(random_bytes(8));$hash=password_hash($password,PASSWORD_DEFAULT);
 foreach(['administrator','environmental_staff','owner'] as $role){$email='phase7-'.$role.'-'.bin2hex(random_bytes(3)).'@example.test';$emails[$role]=$email;$pdo->prepare('INSERT INTO users(role_id,full_name,email,password_hash)VALUES(?,?,?,?)')->execute([$roles[$role],'Phase 7 '.$role,$email,$hash]);$ids['users'][$role]=(int)$pdo->lastInsertId();}
 foreach(['formula','other'] as $which){$code='P7'.strtoupper(bin2hex(random_bytes(5)));$name=$which==='formula'?'=SUM(1,1) Phase 7 TEST DATA':'Phase 7 OTHER TEST DATA';$owner=$ids['users']['owner'];$pdo->prepare('INSERT INTO establishments(registration_code,business_name,owner_user_id,owner_name,address,registration_date,created_by)VALUES(?,?,?,?,?,CURRENT_DATE(),?)')->execute([$code,$name,$owner,'Phase 7 Owner','Test Address',$ids['users']['administrator']]);$ids['sites'][$which]=(int)$pdo->lastInsertId();}
 $pdo->prepare('INSERT INTO grease_traps(establishment_id,trap_code,name,capacity_liters,low_threshold,medium_threshold,high_threshold,critical_threshold,empty_distance_cm,full_distance_cm)VALUES(?,?,?,50,20,50,75,90,30,5)')->execute([$ids['sites']['formula'],'P7T'.strtoupper(bin2hex(random_bytes(4))),'Phase 7 Trap']);$trap=(int)$pdo->lastInsertId();$ids['traps'][]=$trap;
 $pdo->prepare('INSERT INTO devices(device_code,name,last_seen_at)VALUES(?,?,UTC_TIMESTAMP())')->execute(['P7D'.strtoupper(bin2hex(random_bytes(4))),'Phase 7 Device']);$device=(int)$pdo->lastInsertId();$ids['devices'][]=$device;
 $pdo->prepare('INSERT INTO device_assignments(device_id,grease_trap_id,started_at)VALUES(?,?,DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 DAY))')->execute([$device,$trap]);$assignment=(int)$pdo->lastInsertId();$ids['assignments'][]=$assignment;
 for($i=0;$i<30;$i++){$pdo->prepare('INSERT INTO sensor_readings(device_assignment_id,ultrasonic_distance_cm,waste_level_percent,temperature_c,flow_rate_lpm,level_status,reading_uuid,recorded_at)VALUES(?,?,?,?,?,?,?,DATE_SUB(UTC_TIMESTAMP(),INTERVAL ? MINUTE))')->execute([$assignment,20-$i/10,40+$i,25+$i/10,1+$i/100,$i>25?'CRITICAL':'NORMAL',sprintf('00000000-0000-4000-8000-%012d',$i),$i]);$ids['readings'][]=(int)$pdo->lastInsertId();}
 $pdo->prepare("INSERT INTO alerts(device_assignment_id,sensor_reading_id,alert_type,severity,message,status,first_triggered_at,last_triggered_at)VALUES(?,?,'CRITICAL_LEVEL','CRITICAL','Phase 7 TEST DATA','ACTIVE',UTC_TIMESTAMP(),UTC_TIMESTAMP())")->execute([$assignment,end($ids['readings'])]);$ids['alerts'][]=(int)$pdo->lastInsertId();
 foreach([['L',5],['kg',2]] as [$unit,$quantity]){$code='P7S'.strtoupper(bin2hex(random_bytes(5)));$pdo->prepare("INSERT INTO oil_surrenders(transaction_code,establishment_id,grease_trap_id,device_id,submitted_by,surrendered_at,oil_quantity,oil_unit,status,verification_status,reviewed_by,reviewed_at,approved_at)VALUES(?,?,?,?,?,UTC_TIMESTAMP(),?,?,'APPROVED','VERIFIED',?,UTC_TIMESTAMP(),UTC_TIMESTAMP())")->execute([$code,$ids['sites']['formula'],$trap,$device,$ids['users']['owner'],$quantity,$unit,$ids['users']['administrator']]);$ids['surrenders'][$unit]=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO incentive_rules(name,minimum_oil_quantity,oil_unit,rice_reward_quantity,rice_unit,calculation_type,effective_date,created_by,is_test)VALUES(?,?,?,?,?,'FIXED_TRANSACTION',CURRENT_DATE(),?,1)")->execute(['Phase 7 '.$unit,1,$unit,$unit==='L'?2:500,$unit==='L'?'kg':'g',$ids['users']['administrator']]);$rule=(int)$pdo->lastInsertId();$ids['rules'][]=$rule;$pdo->prepare("INSERT INTO incentive_transactions(transaction_code,oil_surrender_id,establishment_id,owner_user_id,rule_id,oil_quantity,oil_unit,rule_name_snapshot,oil_threshold_snapshot,rule_reward_snapshot,calculation_type_snapshot,qualifying_blocks,rice_quantity,rice_unit,status,calculated_by,processed_at,distributed_by,distributed_at)VALUES(?,?,?,?,?,?,?,?,?,?,'FIXED_TRANSACTION',1,?,?,'DISTRIBUTED',?,UTC_TIMESTAMP(),?,UTC_TIMESTAMP())")->execute(['P7I'.strtoupper(bin2hex(random_bytes(5))),$ids['surrenders'][$unit],$ids['sites']['formula'],$ids['users']['owner'],$rule,$quantity,$unit,'Phase 7 '.$unit,1,$unit==='L'?2:500,$unit==='L'?2:500,$unit==='L'?'kg':'g',$ids['users']['administrator'],$ids['users']['administrator']]);$ids['incentives'][]=(int)$pdo->lastInsertId();}
 $pdo->prepare("INSERT INTO compliance_ledger(event_code,event_type,establishment_id,grease_trap_id,device_id,related_record_type,related_record_id,description,event_timestamp,dedupe_key,created_by)VALUES(?,'TEST_EVENT',?,?,?,?,?,?,UTC_TIMESTAMP(),?,?)")->execute(['P7L'.strtoupper(bin2hex(random_bytes(5))),$ids['sites']['formula'],$trap,$device,'establishments',$ids['sites']['formula'],'Phase 7 TEST DATA','P7:'.bin2hex(random_bytes(8)),$ids['users']['administrator']]);$ids['ledger'][]=(int)$pdo->lastInsertId();
 audit('PHASE7_TEST_ACTION',$ids['users']['administrator'],'establishments',$ids['sites']['formula']);$ids['audit'][]=(int)$pdo->lastInsertId();
 $baseFilter=['period'=>'today','establishment_id'=>$ids['sites']['formula']];
 foreach(['telemetry','alerts','surrenders','incentives','distribution','devices','traps','ledger','audit'] as $type){$input=$baseFilter+['report'=>$type];if($type==='audit')$input=['report'=>'audit','period'=>'today','user_id'=>$ids['users']['administrator']];$d=phase7_report_data($pdo,phase7_report_filters($input));p7_check($d['total']>=1,ucfirst($type).' report filter returns fixture records');}
 $telemetry=phase7_report_data($pdo,phase7_report_filters($baseFilter+['report'=>'telemetry','device_id'=>$device,'page_size'=>25]));p7_check($telemetry['total']===30&&count($telemetry['rows'])===25&&$telemetry['pages']===2,'Large telemetry results paginate at the selected page size');
 $other=phase7_report_data($pdo,phase7_report_filters(['report'=>'telemetry','period'=>'today','establishment_id'=>$ids['sites']['other']]));p7_check($other['total']===0&&$other['rows']===[],'Empty and establishment-isolated report is honest');
 $alert=phase7_report_data($pdo,phase7_report_filters($baseFilter+['report'=>'alerts','status'=>'CRITICAL']));p7_check($alert['total']===1&&$alert['rows'][0]['severity']==='CRITICAL','Alert severity filter works');
 $oil=phase7_report_data($pdo,phase7_report_filters($baseFilter+['report'=>'surrenders','status'=>'APPROVED']));$oilLabels=implode('|',array_column($oil['summary'],'label'));p7_check(str_contains($oilLabels,'(L)')&&str_contains($oilLabels,'(kg)'),'Different oil units remain separate in filtered summaries');
 $rice=phase7_report_data($pdo,phase7_report_filters($baseFilter+['report'=>'incentives','status'=>'DISTRIBUTED']));$riceLabels=implode('|',array_column($rice['summary'],'label'));p7_check(str_contains($riceLabels,'(g)')&&str_contains($riceLabels,'(kg)'),'Different rice units remain separate in filtered summaries');
 $detail=phase7_establishment_detail($pdo,phase7_report_filters($baseFilter+['report'=>'establishment']));p7_check($detail['info']['business_name']==='=SUM(1,1) Phase 7 TEST DATA'&&count($detail['traps'])===1,'Establishment detail combines registration and monitoring records');
 $anonymous=p7_http(null,$base.'/admin/reports.php');p7_check($anonymous['status']===303&&str_contains($anonymous['headers'],'public/login.php'),'Reports require authentication');$anonymousExport=p7_http(null,$base.'/admin/report-export.php?format=csv&report=overview&period=today');p7_check($anonymousExport['status']===303,'Direct export URL independently requires authentication');
 $composerPrivate=p7_http(null,$base.'/composer.json');$vendorPrivate=p7_http(null,$base.'/vendor/autoload.php');p7_check(in_array($composerPrivate['status'],[403,404],true)&&in_array($vendorPrivate['status'],[403,404],true),'Composer metadata and vendor source are blocked from HTTP access');
 $staff=p7_login($base,$emails['environmental_staff'],$password);p7_check(curl_getinfo($staff,CURLINFO_RESPONSE_CODE)===303,'Environmental staff can authenticate');$page=p7_http($staff,$base.'/admin/reports.php?report=telemetry&period=today&establishment_id='.$ids['sites']['formula']);p7_check($page['status']===200&&str_contains($page['body'],'Telemetry readings'),'Authorized staff can open filtered reports');
 $csv=p7_http($staff,$base.'/admin/report-export.php?format=csv&report=overview&period=today&establishment_id='.$ids['sites']['formula']);p7_check($csv['status']===200&&str_contains($csv['headers'],'text/csv')&&str_contains($csv['body'],"'=SUM(1,1) Phase 7 TEST DATA")&&!str_contains($csv['body'],'Phase 7 OTHER TEST DATA'),'CSV contains only filtered records and neutralizes formula content');
 $pdf=p7_http($staff,$base.'/admin/report-export.php?format=pdf&report=overview&period=today&establishment_id='.$ids['sites']['formula']);p7_check($pdf['status']===200&&str_starts_with($pdf['body'],'%PDF'),'PDF export returns a valid PDF response');
 $audited=(int)$pdo->query("SELECT COUNT(*) FROM audit_logs WHERE user_id=".(int)$ids['users']['environmental_staff']." AND action IN ('REPORT_CSV_EXPORTED','REPORT_PDF_EXPORTED') AND record_type='report:overview' AND created_at>='$testStart'")->fetchColumn();p7_check($audited===2,'CSV and PDF export actions are audited with report type');
 $owner=p7_login($base,$emails['owner'],$password);p7_check(curl_getinfo($owner,CURLINFO_RESPONSE_CODE)===200,'Owner is denied administrative website authentication');curl_close($owner);curl_close($staff);
 echo PHP_EOL.$checks." Phase 7 checks passed.\n";
}finally{
 if($pdo->inTransaction())$pdo->rollBack();$userIds=array_values($ids['users']);if($userIds){$marks=implode(',',array_fill(0,count($userIds),'?'));$pdo->prepare("DELETE FROM audit_logs WHERE user_id IN ($marks)")->execute($userIds);}
 foreach($ids['incentives'] as $id)$pdo->prepare('DELETE FROM incentive_transactions WHERE id=?')->execute([$id]);foreach($ids['surrenders'] as $id)$pdo->prepare('DELETE FROM oil_surrenders WHERE id=?')->execute([$id]);foreach($ids['rules'] as $id)$pdo->prepare('DELETE FROM incentive_rules WHERE id=?')->execute([$id]);foreach($ids['ledger'] as $id)$pdo->prepare('DELETE FROM compliance_ledger WHERE id=?')->execute([$id]);foreach($ids['alerts'] as $id)$pdo->prepare('DELETE FROM alerts WHERE id=?')->execute([$id]);foreach(array_reverse($ids['readings']) as $id)$pdo->prepare('DELETE FROM sensor_readings WHERE id=?')->execute([$id]);foreach($ids['assignments'] as $id)$pdo->prepare('DELETE FROM device_assignments WHERE id=?')->execute([$id]);foreach($ids['devices'] as $id)$pdo->prepare('DELETE FROM devices WHERE id=?')->execute([$id]);foreach($ids['traps'] as $id)$pdo->prepare('DELETE FROM grease_traps WHERE id=?')->execute([$id]);foreach($ids['sites'] as $id)$pdo->prepare('DELETE FROM establishments WHERE id=?')->execute([$id]);foreach($emails as $email)$pdo->prepare('DELETE FROM login_attempts WHERE email_hash=?')->execute([hash('sha256',strtolower($email))]);foreach(array_reverse($ids['users']) as $id)$pdo->prepare('DELETE FROM users WHERE id=?')->execute([$id]);$pdo->prepare("DELETE FROM audit_logs WHERE action='LOGIN_FAILED' AND created_at>=?")->execute([$testStart]);
}
