<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'||!in_array('--allow-local-fixtures',$argv,true))exit("Usage: php tests/phase5.php --allow-local-fixtures\n");
require dirname(__DIR__).'/includes/bootstrap.php';
require_once dirname(__DIR__).'/includes/oil-surrender.php';
if($config['environment']!=='development')throw new RuntimeException('Development fixtures only.');
$base=rtrim((string)$config['test_base_url'],'/');if(!filter_var($base,FILTER_VALIDATE_URL))throw new RuntimeException('Configure test_base_url.');
$pdo=db();$checks=0;$ids=['users'=>[],'sites'=>[],'traps'=>[],'devices'=>[],'assignments'=>[],'surrenders'=>[]];$files=[];$emails=[];$originalSettings=phase5_settings($pdo);
function p5_check(bool $ok,string $label):void{global$checks;if(!$ok)throw new RuntimeException('FAIL: '.$label);$checks++;echo 'PASS: '.$label.PHP_EOL;}
function p5_uuid():string{$hex=bin2hex(random_bytes(16));return substr($hex,0,8).'-'.substr($hex,8,4).'-4'.substr($hex,13,3).'-a'.substr($hex,17,3).'-'.substr($hex,20,12);}
function p5_call(string $path,string $method='GET',?string $token=null,?array $fields=null):array{global$base;$curl=curl_init($base.$path);$headers=[];if($token!==null)$headers[]='Authorization: Bearer '.$token;curl_setopt_array($curl,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>20,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$headers]);if($fields!==null)curl_setopt($curl,CURLOPT_POSTFIELDS,$fields);$body=curl_exec($curl);if($body===false)throw new RuntimeException(curl_error($curl));return['status'=>curl_getinfo($curl,CURLINFO_RESPONSE_CODE),'type'=>curl_getinfo($curl,CURLINFO_CONTENT_TYPE),'body'=>$body,'json'=>json_decode($body,true)];}
function p5_token(PDO $pdo,int $userId,string $passwordHash):string{$token=bin2hex(random_bytes(32));$pdo->prepare('INSERT INTO mobile_tokens(user_id,token_hash,password_fingerprint,expires_at)VALUES(?,?,?,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 1 HOUR))')->execute([$userId,hash('sha256',$token),hash('sha256',$passwordHash)]);return$token;}
function p5_login(CurlHandle $curl,string $email,string $password):void{global$base;curl_setopt_array($curl,[CURLOPT_URL=>$base.'/public/login.php',CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_COOKIEFILE=>'',CURLOPT_FOLLOWLOCATION=>false]);$raw=curl_exec($curl);$size=curl_getinfo($curl,CURLINFO_HEADER_SIZE);$body=substr($raw,$size);preg_match('/name="csrf_token" value="([a-f0-9]{64})"/',$body,$match);curl_setopt_array($curl,[CURLOPT_URL=>$base.'/public/login.php',CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query(['csrf_token'=>$match[1]??'','email'=>$email,'password'=>$password]),CURLOPT_HTTPHEADER=>['Content-Type: application/x-www-form-urlencoded']]);curl_exec($curl);if(curl_getinfo($curl,CURLINFO_RESPONSE_CODE)!==303)throw new RuntimeException('Staff login failed.');curl_setopt($curl,CURLOPT_POST,false);}
try{
 p5_check(version_compare(APP_VERSION,'0.7.0','>='),'Application version retains Phase 5 or later');$columns=$pdo->query('SHOW COLUMNS FROM oil_surrenders')->fetchAll(PDO::FETCH_COLUMN);p5_check(!array_diff(['submission_uuid','grease_trap_id','device_id','notes','review_started_at','approved_at','rejected_at','review_version'],$columns),'Migration 006 is applied');
 $roles=$pdo->query('SELECT slug,id FROM roles')->fetchAll(PDO::FETCH_KEY_PAIR);$password='P5!'.bin2hex(random_bytes(8));$hash=password_hash($password,PASSWORD_DEFAULT);
 foreach(['administrator','environmental_staff','owner','owner2'] as $roleName){$role=str_starts_with($roleName,'owner')?'owner':$roleName;$email='phase5-'.$roleName.'-'.bin2hex(random_bytes(3)).'@example.test';$emails[]=$email;$pdo->prepare('INSERT INTO users(role_id,full_name,email,password_hash)VALUES(?,?,?,?)')->execute([$roles[$role],'Phase 5 '.$roleName,$email,$hash]);$ids['users'][$roleName]=(int)$pdo->lastInsertId();}
 foreach(['owner','owner2'] as $index=>$ownerKey){$prefix='P5'.strtoupper(bin2hex(random_bytes(3))).$index;$pdo->prepare('INSERT INTO establishments(registration_code,business_name,owner_user_id,owner_name,address,registration_date,created_by)VALUES(?,?,?,?,?,CURRENT_DATE(),?)')->execute([$prefix.'E','Phase 5 fictional site '.$index,$ids['users'][$ownerKey],'Fictional Owner','Test Address',$ids['users']['administrator']]);$site=(int)$pdo->lastInsertId();$ids['sites'][]=$site;$pdo->prepare('INSERT INTO grease_traps(establishment_id,trap_code,name,capacity_liters,low_threshold,medium_threshold,high_threshold,critical_threshold,empty_distance_cm,full_distance_cm)VALUES(?,?,?,50,20,50,75,90,30,5)')->execute([$site,$prefix.'T','Phase 5 Trap '.$index]);$trap=(int)$pdo->lastInsertId();$ids['traps'][]=$trap;$pdo->prepare("INSERT INTO devices(device_code,name,device_type,last_seen_at)VALUES(?,?,'SIMULATED',UTC_TIMESTAMP())")->execute([$prefix.'D','Phase 5 Device '.$index]);$device=(int)$pdo->lastInsertId();$ids['devices'][]=$device;$pdo->prepare('INSERT INTO device_assignments(device_id,grease_trap_id,started_at)VALUES(?,?,UTC_TIMESTAMP())')->execute([$device,$trap]);$assignment=(int)$pdo->lastInsertId();$ids['assignments'][]=$assignment;if($index===0){$pdo->prepare("INSERT INTO sensor_readings(device_assignment_id,waste_level_percent,ultrasonic_distance_cm,level_status,is_simulated,recorded_at)VALUES(?,80,10,'HIGH',1,DATE_SUB(UTC_TIMESTAMP(),INTERVAL 5 MINUTE)),(?,35,21.25,'LOW',1,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 5 MINUTE))")->execute([$assignment,$assignment]);}}
 $token1=p5_token($pdo,$ids['users']['owner'],$hash);$token2=p5_token($pdo,$ids['users']['owner2'],$hash);
 $tempDir=sys_get_temp_dir().DIRECTORY_SEPARATOR.'aquasense-p5-'.bin2hex(random_bytes(4));mkdir($tempDir);$valid=$tempDir.DIRECTORY_SEPARATOR.'evidence.png';file_put_contents($valid,base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='));$invalid=$tempDir.DIRECTORY_SEPARATOR.'fake.jpg';file_put_contents($invalid,"not an image");$executable=$tempDir.DIRECTORY_SEPARATOR.'attack.jpg';file_put_contents($executable,"<?php echo 'bad'; ?>");$oversized=$tempDir.DIRECTORY_SEPARATOR.'large.png';copy($valid,$oversized);file_put_contents($oversized,str_repeat("\0",5242881),FILE_APPEND);
 $baseFields=['submission_uuid'=>p5_uuid(),'oil_quantity'=>'5','oil_unit'=>'L','grease_trap_id'=>(string)$ids['traps'][0],'notes'=>'Fictional Phase 5 test','photo'=>new CURLFile($valid,'image/png','evidence.png'),'status'=>'APPROVED'];
 p5_check(p5_call('/api/mobile/oil-surrender.php','POST',null,$baseFields)['status']===401,'Unauthenticated submission is rejected');
 $wrong=$baseFields;$wrong['submission_uuid']=p5_uuid();$wrong['grease_trap_id']=(string)$ids['traps'][1];p5_check(p5_call('/api/mobile/oil-surrender.php','POST',$token1,$wrong)['status']===422,'Owner cannot submit for another establishment');
 foreach([['0','L','Zero quantity is rejected'],['-1','L','Negative quantity is rejected'],['5','gal','Invalid unit is rejected']] as [$quantity,$unit,$label]){$fields=$baseFields;$fields['submission_uuid']=p5_uuid();$fields['oil_quantity']=$quantity;$fields['oil_unit']=$unit;p5_check(p5_call('/api/mobile/oil-surrender.php','POST',$token1,$fields)['status']===422,$label);}
 $missing=$baseFields;$missing['submission_uuid']=p5_uuid();unset($missing['photo']);p5_check(p5_call('/api/mobile/oil-surrender.php','POST',$token1,$missing)['status']===422,'Missing photo is rejected');
 foreach([[$invalid,'image/jpeg','invalid.jpg','Invalid MIME type is rejected'],[$executable,'image/jpeg','attack.jpg','Executable disguised as image is rejected'],[$oversized,'image/png','large.png','Oversized image is rejected']] as [$path,$mime,$name,$label]){$fields=$baseFields;$fields['submission_uuid']=p5_uuid();$fields['photo']=new CURLFile($path,$mime,$name);$status=p5_call('/api/mobile/oil-surrender.php','POST',$token1,$fields)['status'];p5_check($label==='Oversized image is rejected'?in_array($status,[413,422],true):$status===422,$label);}
 $validUuid=p5_uuid();$fields=$baseFields;$fields['submission_uuid']=$validUuid;$response=p5_call('/api/mobile/oil-surrender.php','POST',$token1,$fields);p5_check($response['status']===201&&($response['json']['success']??false),'Authenticated owner can submit valid evidence');$record=$response['json']['data']['surrender'];$ids['surrenders'][]=$record['id'];p5_check($record['status']==='PENDING','New submission starts as PENDING and ignores client status');p5_check(preg_match('/^OS-\d{8}-[A-F0-9]{8}$/D',$record['transaction_code'])===1,'Transaction code is human-readable and unique');
 $photoRow=$pdo->query('SELECT * FROM oil_surrender_photos WHERE oil_surrender_id='.(int)$record['id'])->fetch();$files[]=$photoRow['file_path'];p5_check($photoRow&&$photoRow['mime_type']==='image/png'&&$photoRow['file_size']>0&&$photoRow['file_path']!=='evidence.png','Valid photo is stored with safe metadata and random path');
 $retry=p5_call('/api/mobile/oil-surrender.php','POST',$token1,$fields);p5_check($retry['status']===200&&($retry['json']['data']['idempotent_replay']??false),'Idempotent retry does not create a duplicate');p5_check((int)$pdo->query("SELECT COUNT(*) FROM oil_surrenders WHERE submission_uuid=".$pdo->quote($validUuid))->fetchColumn()===1,'Submission UUID is unique in the database');
 $history=p5_call('/api/mobile/oil-surrenders.php','GET',$token1);p5_check($history['status']===200&&count($history['json']['data']['surrenders'])===1,'Owner history returns owned records');$detail=p5_call('/api/mobile/oil-surrender.php?id='.$record['id'],'GET',$token1);p5_check($detail['status']===200&&$detail['json']['data']['surrender']['id']===$record['id'],'Owner can read owned surrender detail');p5_check(p5_call('/api/mobile/oil-surrender.php?id='.$record['id'],'GET',$token2)['status']===404,'Owner cannot read another owner surrender');
 $photoOk=p5_call('/api/mobile/oil-surrender-photo.php?id='.$photoRow['id'],'GET',$token1);p5_check($photoOk['status']===200&&str_starts_with((string)$photoOk['type'],'image/png'),'Owner can retrieve protected owned photo');p5_check(p5_call('/api/mobile/oil-surrender-photo.php?id='.$photoRow['id'],'GET',$token2)['status']===404,'Owner cannot retrieve another owner photo');
 $evidence=phase5_sensor_evidence($pdo,phase5_admin_record($pdo,$record['id']));p5_check(count($evidence['readings'])===2&&$evidence['before']&&$evidence['after'],'Hybrid Verification retrieves relevant telemetry');p5_check($evidence['level_change']===-45.0,'Hybrid Verification calculates observed level change without quantity claims');
 $started=phase5_review($pdo,$record['id'],'start_review',$ids['users']['administrator'],0,'');p5_check($started['status']==='UNDER_REVIEW'&&(int)$started['reviewed_by']===$ids['users']['administrator'],'Authorized reviewer can start review');$approved=phase5_review($pdo,$record['id'],'approve',$ids['users']['administrator'],1,'Photo and telemetry reviewed.');p5_check($approved['status']==='APPROVED'&&$approved['approved_at']!==null,'Authorized reviewer can approve');p5_check((int)$pdo->query('SELECT COUNT(*) FROM incentive_transactions WHERE oil_surrender_id='.(int)$record['id'])->fetchColumn()===0,'Approval does not calculate a rice incentive');
 try{phase5_review($pdo,$record['id'],'reject',$ids['users']['administrator'],1,'Stale rejection');p5_check(false,'Concurrent conflicting review is rejected');}catch(Phase5ConflictException){p5_check(true,'Concurrent conflicting review is rejected');}
 $secondFields=['submission_uuid'=>p5_uuid(),'oil_quantity'=>'2.5','oil_unit'=>'kg','grease_trap_id'=>(string)$ids['traps'][1],'photo'=>new CURLFile($valid,'image/png','second.png')];$secondResponse=p5_call('/api/mobile/oil-surrender.php','POST',$token2,$secondFields);$second=$secondResponse['json']['data']['surrender'];$ids['surrenders'][]=$second['id'];$secondPhoto=$pdo->query('SELECT file_path FROM oil_surrender_photos WHERE oil_surrender_id='.(int)$second['id'])->fetchColumn();$files[]=$secondPhoto;
 $admin=curl_init();p5_login($admin,$emails[0],$password);curl_setopt_array($admin,[CURLOPT_HEADER=>false,CURLOPT_POST=>false,CURLOPT_CUSTOMREQUEST=>'GET',CURLOPT_URL=>$base.'/admin/oil-surrenders.php',CURLOPT_HTTPHEADER=>[]]);$queueBody=curl_exec($admin);p5_check(curl_getinfo($admin,CURLINFO_RESPONSE_CODE)===200&&str_contains($queueBody,$record['transaction_code']),'Administrator review queue loads actual submissions');curl_setopt($admin,CURLOPT_URL,$base.'/admin/oil-surrender-view.php?id='.$record['id']);$viewBody=curl_exec($admin);p5_check(curl_getinfo($admin,CURLINFO_RESPONSE_CODE)===200&&str_contains($viewBody,'Hybrid Verification'),'Hybrid Verification detail page loads');curl_setopt_array($admin,[CURLOPT_POST=>true,CURLOPT_CUSTOMREQUEST=>'POST',CURLOPT_URL=>$base.'/admin/oil-surrender-view.php?id='.$second['id'],CURLOPT_POSTFIELDS=>http_build_query(['action'=>'reject','review_version'=>0,'remarks'=>'Forged']),CURLOPT_HTTPHEADER=>['Content-Type: application/x-www-form-urlencoded']]);curl_exec($admin);p5_check(curl_getinfo($admin,CURLINFO_RESPONSE_CODE)===403&&(string)$pdo->query('SELECT status FROM oil_surrenders WHERE id='.(int)$second['id'])->fetchColumn()==='PENDING','Phase 5 review actions require CSRF');
 try{phase5_review($pdo,$second['id'],'reject',$ids['users']['administrator'],0,'');p5_check(false,'Rejection requires a reason');}catch(Phase5ValidationException){p5_check(true,'Rejection requires a reason');}$rejected=phase5_review($pdo,$second['id'],'reject',$ids['users']['administrator'],0,'Photo does not show surrendered oil.');p5_check($rejected['status']==='REJECTED'&&$rejected['rejected_at']!==null&&$rejected['remarks']!=='','Authorized reviewer can reject with preserved reason');
 $emptyEvidence=phase5_sensor_evidence($pdo,phase5_admin_record($pdo,$second['id']));p5_check($emptyEvidence['readings']===[]&&$emptyEvidence['before']===null,'Missing telemetry produces an honest empty state');
 p5_check((int)$pdo->query("SELECT COUNT(*) FROM audit_logs WHERE record_type='oil_surrenders' AND record_id IN (".implode(',',array_map('intval',$ids['surrenders'])).")")->fetchColumn()>=7,'Submission, photo, and review actions are audited');p5_check((int)$pdo->query("SELECT COUNT(*) FROM compliance_ledger WHERE related_record_type='oil_surrenders' AND related_record_id IN (".implode(',',array_map('intval',$ids['surrenders'])).")")->fetchColumn()>=5,'Major surrender events enter the compliance ledger');
 $staff=curl_init();p5_login($staff,$emails[1],$password);curl_setopt_array($staff,[CURLOPT_URL=>$base.'/admin/oil-surrender-view.php?id='.$second['id'],CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query(['action'=>'approve','review_version'=>1]),CURLOPT_HTTPHEADER=>['Content-Type: application/x-www-form-urlencoded']]);curl_exec($staff);p5_check(curl_getinfo($staff,CURLINFO_RESPONSE_CODE)===403,'Environmental staff cannot change review status');
 phase5_update_settings($pdo,['oil_surrender_max_upload_bytes'=>5242880,'oil_surrender_telemetry_window_hours'=>7],$ids['users']['administrator']);p5_check((int)phase5_settings($pdo)['oil_surrender_telemetry_window_hours']===7,'Hybrid Verification window is configurable');phase5_update_settings($pdo,$originalSettings,$ids['users']['administrator']);p5_check((int)$pdo->query("SELECT COUNT(*) FROM audit_logs WHERE action='OIL_SURRENDER_SETTINGS_UPDATED' AND user_id=".$ids['users']['administrator'])->fetchColumn()>=2,'Oil surrender policy changes are audited');
 echo PHP_EOL.$checks." Phase 5 checks passed.\n";
}finally{
 foreach($files as $relative){$path=storage_path($relative);if(is_file($path))@unlink($path);}
 foreach($ids['surrenders'] as $id){$pdo->prepare("DELETE FROM compliance_ledger WHERE related_record_type='oil_surrenders' AND related_record_id=?")->execute([$id]);$pdo->prepare("DELETE FROM audit_logs WHERE record_type='oil_surrenders' AND record_id=?")->execute([$id]);$pdo->prepare('DELETE FROM oil_surrender_photos WHERE oil_surrender_id=?')->execute([$id]);$pdo->prepare('DELETE FROM oil_surrenders WHERE id=?')->execute([$id]);}
 foreach($ids['assignments'] as $id){$pdo->prepare('DELETE FROM sensor_readings WHERE device_assignment_id=?')->execute([$id]);$pdo->prepare('DELETE FROM alerts WHERE device_assignment_id=?')->execute([$id]);$pdo->prepare('DELETE FROM device_assignments WHERE id=?')->execute([$id]);}
 foreach($ids['devices'] as $id)$pdo->prepare('DELETE FROM devices WHERE id=?')->execute([$id]);foreach($ids['traps'] as $id)$pdo->prepare('DELETE FROM grease_traps WHERE id=?')->execute([$id]);foreach($ids['sites'] as $id){$pdo->prepare("DELETE FROM compliance_ledger WHERE establishment_id=? AND event_type!='DEVELOPMENT_SETUP'")->execute([$id]);$pdo->prepare('DELETE FROM establishments WHERE id=?')->execute([$id]);}
 $pdo->prepare('UPDATE system_settings SET updated_by=NULL WHERE updated_by IN (?,?,?,?)')->execute(array_values($ids['users']));$pdo->prepare('DELETE FROM audit_logs WHERE user_id IN (?,?,?,?)')->execute(array_values($ids['users']));$pdo->prepare('DELETE FROM mobile_tokens WHERE user_id IN (?,?)')->execute([$ids['users']['owner']??0,$ids['users']['owner2']??0]);foreach($emails as $email)$pdo->prepare('DELETE FROM login_attempts WHERE email_hash=?')->execute([hash('sha256',strtolower($email))]);foreach(array_reverse($ids['users']) as $id)$pdo->prepare('DELETE FROM users WHERE id=?')->execute([$id]);if(isset($tempDir)&&is_dir($tempDir)){foreach(glob($tempDir.DIRECTORY_SEPARATOR.'*')?:[] as $file)@unlink($file);@rmdir($tempDir);}
}
