<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'||!in_array('--allow-local-fixtures',$argv,true))exit("Usage: php tests/phase4.php --allow-local-fixtures\n");
require dirname(__DIR__).'/includes/bootstrap.php';require_once dirname(__DIR__).'/includes/telemetry.php';require_once dirname(__DIR__).'/includes/alert-engine.php';require_once dirname(__DIR__).'/includes/monitoring.php';
if($config['environment']!=='development')throw new RuntimeException('Development fixtures only.');$checks=0;$pdo=db();$ids=[];$originalSettings=phase4_numeric_settings($pdo);
function p4_check(bool $ok,string $label):void{global$checks;if(!$ok)throw new RuntimeException('FAIL: '.$label);$checks++;echo 'PASS: '.$label.PHP_EOL;}
function p4_client():CurlHandle{$c=curl_init();curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_COOKIEFILE=>'',CURLOPT_TIMEOUT=>15]);return$c;}
function p4_request(CurlHandle $c,string $path,string $method='GET',?string $body=null,array $headers=[]):array{global$config;$base=rtrim((string)$config['test_base_url'],'/');curl_setopt_array($c,[CURLOPT_URL=>$base.$path,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_POSTFIELDS=>$body,CURLOPT_HTTPHEADER=>$headers]);$raw=curl_exec($c);if($raw===false)throw new RuntimeException(curl_error($c));$size=curl_getinfo($c,CURLINFO_HEADER_SIZE);return['status'=>curl_getinfo($c,CURLINFO_RESPONSE_CODE),'body'=>substr($raw,$size)];}
function p4_csrf(string $body):string{preg_match('/name="csrf_token" value="([a-f0-9]{64})"/',$body,$m);return$m[1]??'';}
function p4_login(CurlHandle $c,string $email,string $password):void{$form=p4_request($c,'/public/login.php');$reply=p4_request($c,'/public/login.php','POST',http_build_query(['csrf_token'=>p4_csrf($form['body']),'email'=>$email,'password'=>$password]),['Content-Type: application/x-www-form-urlencoded']);if($reply['status']!==303)throw new RuntimeException('Phase 4 login failed.');}
function p4_send(PDO $pdo,array $device,array $assignment,float $distance,?float $temperature=null,?float $turbidity=null,?float $flow=null):array{$pdo->prepare('UPDATE devices SET last_seen_at=NULL WHERE id=?')->execute([$device['id']]);$body=['device_id'=>$device['code'],'grease_trap_id'=>$assignment['trap_id'],'ultrasonic_distance'=>$distance,'reading_uuid'=>sprintf('123e4567-e89b-42d3-a456-%012d',random_int(1,999999999999))];if($temperature!==null)$body['temperature']=$temperature;if($turbidity!==null)$body['turbidity']=$turbidity;if($flow!==null)$body['flow_rate']=$flow;return phase3_ingest_telemetry($pdo,$body,$device['key'],true);}
try{
 p4_check(version_compare(APP_VERSION,'0.6.0','>='),'Application retains Phase 4 or newer version');$columns=$pdo->query('SHOW COLUMNS FROM alerts')->fetchAll(PDO::FETCH_COLUMN);p4_check(!array_diff(['sensor_name','threshold_value','first_triggered_at','last_triggered_at','trigger_count','resolution_note','active_alert_key'],$columns),'Phase 4 migration is applied');
 $roles=$pdo->query('SELECT slug,id FROM roles')->fetchAll(PDO::FETCH_KEY_PAIR);$password='P4!'.bin2hex(random_bytes(8));foreach(['administrator','environmental_staff'] as $role){$email='phase4-'.$role.'-'.bin2hex(random_bytes(3)).'@example.test';$ids['emails'][$role]=$email;$pdo->prepare('INSERT INTO users(role_id,full_name,email,password_hash)VALUES(?,?,?,?)')->execute([$roles[$role],'Phase 4 '.$role,$email,password_hash($password,PASSWORD_DEFAULT)]);$ids['users'][$role]=(int)$pdo->lastInsertId();}
 $prefix='P4'.strtoupper(bin2hex(random_bytes(3)));$pdo->prepare('INSERT INTO establishments(registration_code,business_name,owner_name,address,registration_date,created_by)VALUES(?,?,?,?,CURRENT_DATE(),?)')->execute([$prefix.'E','Phase 4 Site','Test Owner','Test Address',$ids['users']['administrator']]);$ids['site']=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO grease_traps(establishment_id,trap_code,name,capacity_liters,low_threshold,medium_threshold,high_threshold,critical_threshold,empty_distance_cm,full_distance_cm)VALUES(?,?,?,60,20,50,75,90,30,5)')->execute([$ids['site'],$prefix.'T','Phase 4 Trap']);$ids['trap']=(int)$pdo->lastInsertId();$key=bin2hex(random_bytes(32));$pdo->prepare('INSERT INTO devices(device_code,name,device_type,api_key_hash)VALUES(?,?,?,?)')->execute([$prefix.'D','Phase 4 ESP32','ESP32 DevKit',hash('sha256',$key)]);$ids['device']=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO device_assignments(device_id,grease_trap_id,started_at)VALUES(?,?,UTC_TIMESTAMP())')->execute([$ids['device'],$ids['trap']]);$ids['assignment']=(int)$pdo->lastInsertId();$device=['id'=>$ids['device'],'code'=>$prefix.'D','key'=>$key];$assignment=['assignment_id'=>$ids['assignment'],'trap_id'=>$ids['trap']];
 p4_send($pdo,$device,$assignment,15);p4_check((int)$pdo->query("SELECT COUNT(*) FROM alerts WHERE device_assignment_id={$ids['assignment']} AND status!='RESOLVED'")->fetchColumn()===0,'Below-threshold reading creates no alert');
 p4_send($pdo,$device,$assignment,10);p4_check((int)$pdo->query("SELECT COUNT(*) FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type='HIGH_LEVEL' AND status='ACTIVE'")->fetchColumn()===1,'High-level reading creates HIGH_LEVEL');
 p4_send($pdo,$device,$assignment,7);p4_check((int)$pdo->query("SELECT COUNT(*) FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type='CRITICAL_LEVEL' AND status='ACTIVE'")->fetchColumn()===1,'Critical reading creates CRITICAL_LEVEL');p4_check((int)$pdo->query("SELECT COUNT(*) FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type='OVERFLOW_WARNING' AND status='ACTIVE'")->fetchColumn()===1,'Critical reading creates pre-overflow warning');
 p4_send($pdo,$device,$assignment,6.8);p4_check((int)$pdo->query("SELECT COUNT(*) FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type='CRITICAL_LEVEL' AND status!='RESOLVED'")->fetchColumn()===1,'Repeated critical readings are deduplicated');p4_check((int)$pdo->query("SELECT trigger_count FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type='CRITICAL_LEVEL' AND status!='RESOLVED'")->fetchColumn()===2,'Active alert trigger count updates');p4_check((float)$pdo->query("SELECT sensor_value FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type='CRITICAL_LEVEL' AND status!='RESOLVED'")->fetchColumn()===92.8,'Active alert stores the latest sensor value');p4_send($pdo,$device,$assignment,5);p4_check((int)$pdo->query("SELECT COUNT(*) FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type='OVERFLOW' AND status='ACTIVE'")->fetchColumn()===1,'Overflow reading creates OVERFLOW');
 p4_send($pdo,$device,$assignment,15,42);p4_check((int)$pdo->query("SELECT COUNT(*) FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type='EMULSION_WARNING' AND status='ACTIVE'")->fetchColumn()===1,'Emulsion threshold creates EMULSION_WARNING');p4_check((int)$pdo->query("SELECT COUNT(*) FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type='HIGH_TEMPERATURE' AND status='ACTIVE'")->fetchColumn()===0,'Temperature below high threshold creates no HIGH_TEMPERATURE');
 p4_send($pdo,$device,$assignment,15,46);p4_check((int)$pdo->query("SELECT COUNT(*) FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type='HIGH_TEMPERATURE' AND status='ACTIVE'")->fetchColumn()===1,'High temperature creates HIGH_TEMPERATURE');$beforeNull=(int)$pdo->query("SELECT SUM(trigger_count) FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type IN ('HIGH_TEMPERATURE','EMULSION_WARNING') AND status!='RESOLVED'")->fetchColumn();p4_send($pdo,$device,$assignment,15);$afterNull=(int)$pdo->query("SELECT SUM(trigger_count) FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type IN ('HIGH_TEMPERATURE','EMULSION_WARNING') AND status!='RESOLVED'")->fetchColumn();p4_check($beforeNull===$afterNull,'Null temperature does not create or resolve temperature alerts');p4_send($pdo,$device,$assignment,15,30);p4_check((int)$pdo->query("SELECT COUNT(*) FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type IN ('HIGH_TEMPERATURE','EMULSION_WARNING') AND status!='RESOLVED'")->fetchColumn()===0,'Normal temperature resolves temperature alerts');
 p4_send($pdo,$device,$assignment,15,null,600);p4_check((int)$pdo->query("SELECT COUNT(*) FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type='HIGH_TURBIDITY' AND status='ACTIVE'")->fetchColumn()===1,'High turbidity creates alert');p4_send($pdo,$device,$assignment,15,null,null,12);p4_check((int)$pdo->query("SELECT COUNT(*) FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type='ABNORMAL_FLOW' AND status='ACTIVE'")->fetchColumn()===1,'Abnormal flow creates alert');
 $pdo->prepare("UPDATE devices SET last_seen_at=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 20 MINUTE) WHERE id=?")->execute([$ids['device']]);$pdo->beginTransaction();$offline=phase4_check_offline_devices($pdo);$pdo->commit();p4_check((int)$pdo->query("SELECT COUNT(*) FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type='DEVICE_OFFLINE' AND status='ACTIVE'")->fetchColumn()===1,'Offline checker creates DEVICE_OFFLINE');$pdo->beginTransaction();phase4_check_offline_devices($pdo);$pdo->commit();p4_check((int)$pdo->query("SELECT COUNT(*) FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type='DEVICE_OFFLINE' AND status!='RESOLVED'")->fetchColumn()===1,'Repeated offline check is deduplicated');
 p4_send($pdo,$device,$assignment,15);p4_check((int)$pdo->query("SELECT COUNT(*) FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type='DEVICE_OFFLINE' AND status='RESOLVED'")->fetchColumn()>=1,'Returning telemetry resolves offline alert');
 p4_send($pdo,$device,$assignment,10);$alertId=(int)$pdo->query("SELECT id FROM alerts WHERE device_assignment_id={$ids['assignment']} AND alert_type='HIGH_LEVEL' AND status='ACTIVE' ORDER BY id DESC LIMIT 1")->fetchColumn();phase4_acknowledge_alert($alertId,$ids['users']['administrator']);$ack=$pdo->query("SELECT * FROM alerts WHERE id=$alertId")->fetch();p4_check($ack['status']==='ACKNOWLEDGED'&&(int)$ack['acknowledged_by']===$ids['users']['administrator']&&$ack['acknowledged_at']!==null,'Acknowledgment records user and time');phase4_resolve_alert($alertId,$ids['users']['administrator'],'Trap serviced.');$resolved=$pdo->query("SELECT * FROM alerts WHERE id=$alertId")->fetch();p4_check($resolved['status']==='RESOLVED'&&(int)$resolved['resolved_by']===$ids['users']['administrator']&&$resolved['resolution_note']==='Trap serviced.','Resolution preserves user, time, and note');
 try{phase4_validate_settings(['emulsion_temperature_threshold'=>40,'high_temperature_threshold'=>45,'high_turbidity_threshold'=>500,'flow_rate_min'=>10,'flow_rate_max'=>5,'overflow_threshold'=>100,'device_offline_timeout_minutes'=>10]);p4_check(false,'Invalid threshold sequence rejected');}catch(InvalidArgumentException){p4_check(true,'Invalid threshold sequence rejected');}
 $update=$originalSettings;$update['device_offline_timeout_minutes']=11;phase4_update_settings($update,$ids['users']['administrator']);p4_check((int)$pdo->query("SELECT COUNT(*) FROM audit_logs WHERE user_id={$ids['users']['administrator']} AND action='THRESHOLDS_UPDATED'")->fetchColumn()===1,'Threshold update is audited');phase4_update_settings($originalSettings,$ids['users']['administrator']);
 p4_check((int)$pdo->query("SELECT COUNT(*) FROM audit_logs WHERE user_id={$ids['users']['administrator']} AND action='ALERT_ACKNOWLEDGED'")->fetchColumn()===1,'Acknowledgment is audited');p4_check((int)$pdo->query("SELECT COUNT(*) FROM audit_logs WHERE user_id={$ids['users']['administrator']} AND action='ALERT_RESOLVED'")->fetchColumn()===1,'Resolution is audited');
 p4_check((int)$pdo->query("SELECT COUNT(*) FROM compliance_ledger WHERE establishment_id={$ids['site']} AND event_type='ALERT_TRIGGERED'")->fetchColumn()>=1,'New alerts enter the Compliance Ledger');p4_check((int)$pdo->query("SELECT COUNT(*) FROM compliance_ledger WHERE related_record_type='alerts' AND related_record_id=$alertId AND event_type='ALERT_ACKNOWLEDGED'")->fetchColumn()===1,'Alert acknowledgment enters the Compliance Ledger');p4_check((int)$pdo->query("SELECT COUNT(*) FROM compliance_ledger WHERE related_record_type='alerts' AND related_record_id=$alertId AND event_type='ALERT_RESOLVED'")->fetchColumn()===1,'Alert resolution enters the Compliance Ledger');
 $monitor=phase3_monitoring_latest();$match=array_values(array_filter($monitor['traps'],fn($t)=>(int)$t['grease_trap_id']===$ids['trap']));p4_check($match&&array_key_exists('active_alerts',$match[0]),'Monitoring exposes active alerts');p4_check(is_file(dirname(__DIR__).'/scripts/check_offline_devices.php'),'Cron-compatible offline checker exists');
 p4_check(p4_request(p4_client(),'/api/admin/alerts.php')['status']===401,'Alert API requires authentication');$staff=p4_client();p4_login($staff,$ids['emails']['environmental_staff'],$password);p4_check(p4_request($staff,'/admin/alert-view.php?id='.$alertId,'POST',http_build_query(['action'=>'resolve']),['Content-Type: application/x-www-form-urlencoded'])['status']===403,'Environmental staff cannot change alert state');$admin=p4_client();p4_login($admin,$ids['emails']['administrator'],$password);p4_check(p4_request($admin,'/admin/alert-view.php?id='.$alertId,'POST',http_build_query(['action'=>'resolve']),['Content-Type: application/x-www-form-urlencoded'])['status']===403,'Alert actions require CSRF');p4_check(p4_request($admin,'/admin/alerts.php')['status']===200,'Authenticated alert history page loads');
 echo PHP_EOL.$checks." Phase 4 checks passed.\n";
}finally{
 if(isset($ids['site']))$pdo->prepare('DELETE FROM compliance_ledger WHERE establishment_id=?')->execute([$ids['site']]);if(isset($ids['assignment'])){$pdo->prepare('DELETE FROM alerts WHERE device_assignment_id=?')->execute([$ids['assignment']]);$pdo->prepare('DELETE FROM sensor_readings WHERE device_assignment_id=?')->execute([$ids['assignment']]);$pdo->prepare('DELETE FROM device_assignments WHERE id=?')->execute([$ids['assignment']]);}$pdo->prepare('UPDATE system_settings SET updated_by=NULL WHERE updated_by IN (?,?)')->execute([$ids['users']['administrator']??0,$ids['users']['environmental_staff']??0]);$pdo->prepare('DELETE FROM audit_logs WHERE user_id IN (?,?)')->execute([$ids['users']['administrator']??0,$ids['users']['environmental_staff']??0]);if(isset($ids['device']))$pdo->prepare('DELETE FROM devices WHERE id=?')->execute([$ids['device']]);if(isset($ids['trap']))$pdo->prepare('DELETE FROM grease_traps WHERE id=?')->execute([$ids['trap']]);if(isset($ids['site']))$pdo->prepare('DELETE FROM establishments WHERE id=?')->execute([$ids['site']]);foreach($ids['emails']??[] as $email)$pdo->prepare('DELETE FROM login_attempts WHERE email_hash=?')->execute([hash('sha256',strtolower($email))]);foreach($ids['users']??[] as $id)$pdo->prepare('DELETE FROM users WHERE id=?')->execute([$id]);
}
