<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'||!in_array('--allow-local-fixtures',$argv,true))exit("Usage: php tests/phase6.php --allow-local-fixtures\n");
require dirname(__DIR__).'/includes/bootstrap.php';require_once dirname(__DIR__).'/includes/incentive.php';
if($config['environment']!=='development')throw new RuntimeException('Development fixtures only.');
$base=rtrim((string)$config['test_base_url'],'/');if(!filter_var($base,FILTER_VALIDATE_URL))throw new RuntimeException('Configure test_base_url.');
$pdo=db();$checks=0;$ids=['users'=>[],'sites'=>[],'traps'=>[],'rules'=>[],'surrenders'=>[],'incentives'=>[]];$emails=[];
function p6_check(bool $ok,string $label):void{global$checks;if(!$ok)throw new RuntimeException('FAIL: '.$label);$checks++;echo 'PASS: '.$label.PHP_EOL;}
function p6_expect(string $class,callable $work,string $label):void{try{$work();p6_check(false,$label);}catch(Throwable$e){p6_check($e instanceof$class,$label);}}
function p6_surrender(PDO $pdo,array &$ids,int $site,int $owner,string $status,float $quantity,string $unit='L'):int{$code='P6-'.strtoupper(bin2hex(random_bytes(6)));$q=$pdo->prepare('INSERT INTO oil_surrenders(transaction_code,establishment_id,submitted_by,surrendered_at,oil_quantity,oil_unit,status,approved_at)VALUES(?,?,?,UTC_TIMESTAMP(),?,?,?,IF(?=\'APPROVED\',UTC_TIMESTAMP(),NULL))');$q->execute([$code,$site,$owner,$quantity,$unit,$status,$status]);$id=(int)$pdo->lastInsertId();$ids['surrenders'][]=$id;return$id;}
function p6_token(PDO$pdo,int$userId,string$hash):string{$token=bin2hex(random_bytes(32));$pdo->prepare('INSERT INTO mobile_tokens(user_id,token_hash,password_fingerprint,expires_at)VALUES(?,?,?,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 1 HOUR))')->execute([$userId,hash('sha256',$token),hash('sha256',$hash)]);return$token;}
function p6_api(string$method,string$path,?string$token):array{global$base;$c=curl_init($base.$path);$headers=[];if($token)$headers[]='Authorization: Bearer '.$token;curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>15,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$headers]);$raw=curl_exec($c);if($raw===false)throw new RuntimeException(curl_error($c));$result=['status'=>curl_getinfo($c,CURLINFO_RESPONSE_CODE),'json'=>json_decode($raw,true)];curl_close($c);return$result;}
function p6_login(string$email,string$password):CurlHandle{global$base;$c=curl_init();curl_setopt_array($c,[CURLOPT_URL=>$base.'/public/login.php',CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_COOKIEFILE=>'',CURLOPT_FOLLOWLOCATION=>false]);$raw=curl_exec($c);$size=curl_getinfo($c,CURLINFO_HEADER_SIZE);preg_match('/name="csrf_token" value="([a-f0-9]{64})"/',substr($raw,$size),$m);curl_setopt_array($c,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query(['csrf_token'=>$m[1]??'','email'=>$email,'password'=>$password]),CURLOPT_HTTPHEADER=>['Content-Type: application/x-www-form-urlencoded']]);curl_exec($c);if(curl_getinfo($c,CURLINFO_RESPONSE_CODE)!==303)throw new RuntimeException('Phase 6 staff login failed.');curl_setopt_array($c,[CURLOPT_POST=>false,CURLOPT_CUSTOMREQUEST=>'GET',CURLOPT_HEADER=>false]);return$c;}
try{
 p6_check(APP_VERSION==='0.8.0','Application version is 0.8.0');
 $txColumns=$pdo->query('SHOW COLUMNS FROM incentive_transactions')->fetchAll(PDO::FETCH_COLUMN);$ledgerColumns=$pdo->query('SHOW COLUMNS FROM compliance_ledger')->fetchAll(PDO::FETCH_COLUMN);
 p6_check(!array_diff(['transaction_code','establishment_id','owner_user_id','rule_name_snapshot','status_version'],$txColumns),'Phase 6 incentive migration is applied');p6_check(!array_diff(['event_code','event_timestamp','dedupe_key'],$ledgerColumns),'Compliance Ledger migration is applied');
 $roles=$pdo->query('SELECT slug,id FROM roles')->fetchAll(PDO::FETCH_KEY_PAIR);$password='P6!'.bin2hex(random_bytes(8));$hash=password_hash($password,PASSWORD_DEFAULT);
 foreach(['administrator','owner','owner2']as$key){$role=str_starts_with($key,'owner')?'owner':'administrator';$email='phase6-'.$key.'-'.bin2hex(random_bytes(3)).'@example.test';$emails[]=$email;$pdo->prepare('INSERT INTO users(role_id,full_name,email,password_hash)VALUES(?,?,?,?)')->execute([$roles[$role],'Phase 6 '.$key,$email,$hash]);$ids['users'][$key]=(int)$pdo->lastInsertId();}
 foreach(['owner','owner2']as$i=>$key){$code='P6'.strtoupper(bin2hex(random_bytes(4))).$i;$pdo->prepare('INSERT INTO establishments(registration_code,business_name,owner_user_id,owner_name,address,registration_date,created_by)VALUES(?,?,?,?,?,CURRENT_DATE(),?)')->execute([$code,'Phase 6 TEST DATA '.$i,$ids['users'][$key],'Phase 6 Owner','Test Address',$ids['users']['administrator']]);$site=(int)$pdo->lastInsertId();$ids['sites'][]=$site;$pdo->prepare('INSERT INTO grease_traps(establishment_id,trap_code,name,capacity_liters,low_threshold,medium_threshold,high_threshold,critical_threshold)VALUES(?,?,?,50,20,50,75,90)')->execute([$site,$code.'T','Phase 6 Trap']);$ids['traps'][]=(int)$pdo->lastInsertId();}
 $pending=p6_surrender($pdo,$ids,$ids['sites'][0],$ids['users']['owner'],'PENDING',10);$review=p6_surrender($pdo,$ids,$ids['sites'][0],$ids['users']['owner'],'UNDER_REVIEW',10);$rejected=p6_surrender($pdo,$ids,$ids['sites'][0],$ids['users']['owner'],'REJECTED',10);$approved=p6_surrender($pdo,$ids,$ids['sites'][0],$ids['users']['owner'],'APPROVED',10);$missing=p6_surrender($pdo,$ids,$ids['sites'][0],$ids['users']['owner'],'APPROVED',2.5,'kg');
 foreach([[$pending,'PENDING'],[$review,'UNDER_REVIEW'],[$rejected,'REJECTED']]as[$sid,$state])p6_expect(Phase6ValidationException::class,fn()=>phase6_process_incentive($pdo,$sid,$ids['users']['administrator']),$state.' surrender cannot receive an incentive');
 p6_expect(Phase6ValidationException::class,fn()=>phase6_process_incentive($pdo,$approved,$ids['users']['administrator']),'Missing rule produces a clear processing error');
 p6_expect(Phase6ValidationException::class,fn()=>phase6_save_rule($pdo,['name'=>'Invalid','minimum_oil_quantity'=>0,'oil_unit'=>'L','rice_reward_quantity'=>2,'rice_unit'=>'kg','calculation_type'=>'FIXED_PER_THRESHOLD','effective_date'=>gmdate('Y-m-d'),'is_active'=>1],$ids['users']['administrator']),'Invalid zero threshold is rejected');p6_expect(Phase6ValidationException::class,fn()=>phase6_save_rule($pdo,['name'=>'Invalid dates','minimum_oil_quantity'=>5,'oil_unit'=>'L','rice_reward_quantity'=>2,'rice_unit'=>'kg','calculation_type'=>'FIXED_PER_THRESHOLD','effective_date'=>gmdate('Y-m-d'),'end_date'=>gmdate('Y-m-d'),'is_active'=>1],$ids['users']['administrator']),'Effective end date must be after the start date');
 $ruleInput=['name'=>'DEVELOPMENT TEST DATA: 5 L to 2 kg','minimum_oil_quantity'=>5,'oil_unit'=>'L','rice_reward_quantity'=>2,'rice_unit'=>'kg','calculation_type'=>'FIXED_PER_THRESHOLD','effective_date'=>gmdate('Y-m-d'),'is_active'=>1,'is_test'=>1];$rule=phase6_save_rule($pdo,$ruleInput,$ids['users']['administrator']);$ids['rules'][]=$rule;
 p6_expect(Phase6ValidationException::class,fn()=>phase6_save_rule($pdo,$ruleInput+['name'=>'Overlap'],$ids['users']['administrator']),'Overlapping active rule is rejected');
 p6_check(phase6_applicable_rule($pdo,10,'L')['id']===$rule,'Correct active rule is selected');p6_check(phase6_applicable_rule($pdo,10,'kg')===null,'Incompatible oil unit does not use the L rule');
 $record=phase6_process_incentive($pdo,$approved,$ids['users']['administrator']);$ids['incentives'][]=(int)$record['id'];p6_check($record['status']==='CALCULATED','APPROVED surrender creates a CALCULATED incentive');p6_check((float)$record['rice_quantity']===4.0&&(int)$record['qualifying_blocks']===2,'10 L calculates as two complete blocks and 4 kg');p6_check((int)$record['calculated_by']===$ids['users']['administrator'],'Incentive transaction records its processor');
 p6_expect(Phase6ConflictException::class,fn()=>phase6_process_incentive($pdo,$approved,$ids['users']['administrator']),'Application prevents duplicate incentive processing');
 p6_expect(PDOException::class,function()use($pdo,$record){$q=$pdo->prepare("INSERT INTO incentive_transactions(transaction_code,oil_surrender_id,establishment_id,owner_user_id,rule_id,oil_quantity,oil_unit,rule_name_snapshot,oil_threshold_snapshot,rule_reward_snapshot,calculation_type_snapshot,qualifying_blocks,rice_quantity,rice_unit,status,calculated_by,processed_at)SELECT CONCAT(transaction_code,'X'),oil_surrender_id,establishment_id,owner_user_id,rule_id,oil_quantity,oil_unit,rule_name_snapshot,oil_threshold_snapshot,rule_reward_snapshot,calculation_type_snapshot,qualifying_blocks,rice_quantity,rice_unit,status,calculated_by,processed_at FROM incentive_transactions WHERE id=?");$q->execute([$record['id']]);},'Database unique constraint prevents concurrent duplicate reward');
 $ruleInput['rice_reward_quantity']=3;$ruleInput['name']='DEVELOPMENT TEST DATA: revised';phase6_save_rule($pdo,$ruleInput,$ids['users']['administrator'],$rule);$snapshot=phase6_incentive_record($pdo,$record['id']);p6_check((float)$snapshot['rule_reward_snapshot']===2.0&&(float)$snapshot['rice_quantity']===4.0,'Historical calculation snapshot survives rule edits');
 $kgRule=phase6_save_rule($pdo,['name'=>'DEVELOPMENT TEST DATA: kg to grams','minimum_oil_quantity'=>1,'oil_unit'=>'kg','rice_reward_quantity'=>500,'rice_unit'=>'g','calculation_type'=>'FIXED_TRANSACTION','effective_date'=>gmdate('Y-m-d'),'is_active'=>1,'is_test'=>1],$ids['users']['administrator']);$ids['rules'][]=$kgRule;$gramRecord=phase6_process_incentive($pdo,$missing,$ids['users']['administrator']);$ids['incentives'][]=(int)$gramRecord['id'];p6_check((float)$gramRecord['rice_quantity']===500.0&&$gramRecord['rice_unit']==='g','Fixed transaction rule calculates one configured reward');
 $distributed=phase6_distribute($pdo,$record['id'],$ids['users']['administrator'],0,'Phase 6 TEST DATA distribution');p6_check($distributed['status']==='DISTRIBUTED'&&(int)$distributed['distributed_by']===$ids['users']['administrator']&&$distributed['distributed_at']!==null,'Distribution records status, user, and time');p6_expect(Phase6ConflictException::class,fn()=>phase6_distribute($pdo,$record['id'],$ids['users']['administrator'],1,''),'Distributed reward cannot be reversed or redistributed');
 $token=p6_token($pdo,$ids['users']['owner'],$hash);$token2=p6_token($pdo,$ids['users']['owner2'],$hash);$api=p6_api('GET','/api/mobile/incentives.php',$token);p6_check($api['status']===200&&($api['json']['success']??false),'Authenticated owner incentive endpoint succeeds');$summaries=$api['json']['data']['summary'];$summaryUnits=array_column($summaries,'unit');sort($summaryUnits);p6_check(count($summaries)===2&&$summaryUnits===['g','kg'],'Different reward units remain separate in the owner summary');p6_check(count($api['json']['data']['transactions'])===2,'Owner sees only own incentive history');$other=p6_api('GET','/api/mobile/incentives.php',$token2);p6_check($other['status']===200&&$other['json']['data']['transactions']===[],'Another owner cannot see incentive records');p6_check(p6_api('POST','/api/mobile/incentives.php',$token)['status']===405,'Owner API cannot mark a reward distributed');
 $calcLedger=(int)$pdo->query("SELECT COUNT(*) FROM compliance_ledger WHERE event_type='INCENTIVE_CALCULATED' AND related_record_id IN (".implode(',',$ids['incentives']).')')->fetchColumn();$distLedger=(int)$pdo->query("SELECT COUNT(*) FROM compliance_ledger WHERE event_type='INCENTIVE_DISTRIBUTED' AND related_record_id=".(int)$record['id'])->fetchColumn();p6_check($calcLedger===2,'One INCENTIVE_CALCULATED ledger event exists per incentive');p6_check($distLedger===1,'One INCENTIVE_DISTRIBUTED ledger event exists');p6_check((int)$pdo->query("SELECT COUNT(*) FROM compliance_ledger WHERE dedupe_key='INCENTIVE_DISTRIBUTED:".(int)$record['id']."'")->fetchColumn()===1,'Ledger dedupe key prevents retry duplicates');
 p6_check((int)$pdo->query("SELECT COUNT(*) FROM audit_logs WHERE action='INCENTIVE_RULE_UPDATED' AND record_id=".$rule)->fetchColumn()>=1,'Rule modification creates an audit entry');p6_check((int)$pdo->query("SELECT COUNT(*) FROM audit_logs WHERE action='INCENTIVE_PROCESSED' AND record_id=".(int)$record['id'])->fetchColumn()===1,'Incentive processing creates one audit entry');p6_check((int)$pdo->query("SELECT COUNT(*) FROM audit_logs WHERE action='INCENTIVE_DISTRIBUTED' AND record_id=".(int)$record['id'])->fetchColumn()===1,'Distribution creates one audit entry');
 $rollback=p6_surrender($pdo,$ids,$ids['sites'][1],$ids['users']['owner2'],'APPROVED',5);$before=(int)$pdo->query('SELECT COUNT(*) FROM incentive_transactions')->fetchColumn();p6_expect(RuntimeException::class,fn()=>phase6_process_incentive($pdo,$rollback,$ids['users']['administrator'],true),'Simulated processing failure rolls back');p6_check((int)$pdo->query('SELECT COUNT(*) FROM incentive_transactions')->fetchColumn()===$before&&!(int)$pdo->query("SELECT COUNT(*) FROM compliance_ledger WHERE dedupe_key LIKE 'INCENTIVE_CALCULATED:%' AND establishment_id=".$ids['sites'][1])->fetchColumn(),'Rollback leaves no incentive or false ledger event');
 $ledgerPage=p6_api('DELETE','/api/mobile/incentives.php',$token);p6_check($ledgerPage['status']===405,'Normal owner endpoint exposes no ledger delete operation');
 $staff=p6_login($emails[0],$password);foreach([['/admin/dashboard.php','Phase 6 Sana Oil incentives'],['/admin/incentives.php','Approved surrenders awaiting incentive'],['/admin/incentive-rules.php','Configurable incentive rules'],['/admin/incentive-view.php?id='.$record['id'],$record['transaction_code']],['/admin/establishment-view.php?id='.$ids['sites'][0],'Incentive transaction history'],['/admin/compliance-ledger.php','Digital Compliance Ledger']]as[$path,$text]){curl_setopt($staff,CURLOPT_URL,$base.$path);$body=curl_exec($staff);p6_check(curl_getinfo($staff,CURLINFO_RESPONSE_CODE)===200&&str_contains($body,$text),'Phase 6 staff page loads: '.$path);}curl_close($staff);
 echo PHP_EOL.$checks." Phase 6 checks passed.\n";
}finally{
 if($pdo->inTransaction())$pdo->rollBack();
 if($ids['incentives']){$marks=implode(',',array_fill(0,count($ids['incentives']),'?'));$pdo->prepare("DELETE FROM compliance_ledger WHERE related_record_type='incentive_transactions' AND related_record_id IN ($marks)")->execute($ids['incentives']);$pdo->prepare("DELETE FROM audit_logs WHERE record_type='incentive_transactions' AND record_id IN ($marks)")->execute($ids['incentives']);}
 foreach($ids['sites']as$site)$pdo->prepare('DELETE FROM compliance_ledger WHERE establishment_id=?')->execute([$site]);foreach($ids['incentives']as$id)$pdo->prepare('DELETE FROM incentive_transactions WHERE id=?')->execute([$id]);foreach($ids['surrenders']as$id){$pdo->prepare("DELETE FROM compliance_ledger WHERE related_record_type='oil_surrenders' AND related_record_id=?")->execute([$id]);$pdo->prepare('DELETE FROM oil_surrenders WHERE id=?')->execute([$id]);}foreach($ids['rules']as$id){$pdo->prepare("DELETE FROM audit_logs WHERE record_type='incentive_rules' AND record_id=?")->execute([$id]);$pdo->prepare('DELETE FROM incentive_rules WHERE id=?')->execute([$id]);}foreach($ids['traps']as$id)$pdo->prepare('DELETE FROM grease_traps WHERE id=?')->execute([$id]);foreach($ids['sites']as$id)$pdo->prepare('DELETE FROM establishments WHERE id=?')->execute([$id]);foreach($ids['users']as$id){$pdo->prepare('DELETE FROM mobile_tokens WHERE user_id=?')->execute([$id]);$pdo->prepare('DELETE FROM audit_logs WHERE user_id=?')->execute([$id]);}foreach($emails as$email)$pdo->prepare('DELETE FROM login_attempts WHERE email_hash=?')->execute([hash('sha256',strtolower($email))]);foreach(array_reverse($ids['users'])as$id)$pdo->prepare('DELETE FROM users WHERE id=?')->execute([$id]);
}
