<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'||!in_array('--allow-local-fixtures',$argv,true))exit("Usage: php tests/phase2.php --allow-local-fixtures\n");
require dirname(__DIR__).'/includes/bootstrap.php';require_once dirname(__DIR__).'/includes/admin-core.php';
if($config['environment']!=='development')throw new RuntimeException('Development fixtures only.');
$base=rtrim((string)$config['test_base_url'],'/');if(!filter_var($base,FILTER_VALIDATE_URL))throw new RuntimeException('Configure test_base_url.');
$checks=0;$userIds=[];$estIds=[];$trapIds=[];$deviceIds=[];$emails=[];$password='Phase2!'.bin2hex(random_bytes(10));
function p2_check(bool $ok,string $label):void{global $checks;if(!$ok)throw new RuntimeException('FAIL: '.$label);$checks++;echo 'PASS: '.$label.PHP_EOL;}
function p2_client():CurlHandle{$c=curl_init();curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_COOKIEFILE=>'',CURLOPT_TIMEOUT=>15]);return $c;}
function p2_request(CurlHandle $c,string $path,?array $data=null):array{global $base;curl_setopt($c,CURLOPT_URL,$base.$path);if($data===null)curl_setopt($c,CURLOPT_HTTPGET,true);else{curl_setopt($c,CURLOPT_POST,true);curl_setopt($c,CURLOPT_POSTFIELDS,http_build_query($data));}$raw=curl_exec($c);if($raw===false)throw new RuntimeException(curl_error($c));$size=curl_getinfo($c,CURLINFO_HEADER_SIZE);return['status'=>curl_getinfo($c,CURLINFO_RESPONSE_CODE),'headers'=>substr($raw,0,$size),'body'=>substr($raw,$size)];}
function p2_token(array $response):string{preg_match('/name="csrf_token" value="([a-f0-9]{64})"/',$response['body'],$m);if(!isset($m[1]))throw new RuntimeException('Missing CSRF token.');return$m[1];}
function p2_login(CurlHandle $c,string $email,string $password):void{$form=p2_request($c,'/public/login.php');$reply=p2_request($c,'/public/login.php',['csrf_token'=>p2_token($form),'email'=>$email,'password'=>$password]);p2_check($reply['status']===303,'Authenticated administrator login for Phase 2 tests');}
function p2_expect_validation(callable $call,string $message,string $label):void{try{$call();p2_check(false,$label);}catch(Phase2ValidationException $e){p2_check(in_array($message,$e->errors,true),$label);}}
try{
 $pdo=db();p2_check(APP_VERSION==='0.4.0','Application version is 0.4.0');
 $columns=$pdo->query('SHOW COLUMNS FROM establishments')->fetchAll(PDO::FETCH_COLUMN);p2_check(in_array('notes',$columns,true),'Phase 2 notes migration is applied');
 $roles=$pdo->query('SELECT slug,id FROM roles')->fetchAll(PDO::FETCH_KEY_PAIR);
 foreach(['administrator','environmental_staff'] as $role){$email='phase2-'.$role.'-'.bin2hex(random_bytes(4)).'@example.test';$emails[]=$email;$q=$pdo->prepare('INSERT INTO users(role_id,full_name,email,password_hash)VALUES(?,?,?,?)');$q->execute([$roles[$role],$role==='administrator'?'<script>alert(2)</script> Admin':'Read Only Staff',$email,password_hash($password,PASSWORD_DEFAULT)]);$userIds[$role]=(int)$pdo->lastInsertId();}
 foreach(['/admin/dashboard.php','/admin/establishments.php','/admin/establishment-view.php?id=1','/admin/grease-traps.php','/admin/grease-trap-view.php?id=1','/admin/devices.php','/admin/device-view.php?id=1'] as $path){$r=p2_request(p2_client(),$path);p2_check($r['status']===303&&str_contains($r['headers'],'/public/login.php'),'Anonymous access blocked: '.$path);}
 $prefix='P2'.strtoupper(bin2hex(random_bytes(3)));$injection="' OR 1=1 -- <script>alert(1)</script>";
 $estIds[]=$est1=phase2_create_establishment(['registration_code'=>$prefix.'-E1','business_name'=>$injection,'owner_name'=>'<script>alert(3)</script> Owner','address'=>'Fictional test address','contact_number'=>'+63 912 345 6789','email'=>'owner@example.test','registration_date'=>'2026-09-27','notes'=>'Temporary Phase 2 fixture'],$userIds['administrator']);
 p2_check((int)$pdo->query('SELECT COUNT(*) FROM establishments WHERE id='.(int)$est1.' AND business_name='.$pdo->quote($injection))->fetchColumn()===1,'SQL-like establishment input is stored as data through prepared statements');
 phase2_update_establishment($est1,['registration_code'=>$prefix.'-E1','business_name'=>$injection,'owner_name'=>'Updated Owner','address'=>'Updated fictional address','contact_number'=>'09123456789','email'=>'updated@example.test','registration_date'=>'2026-09-27','notes'=>'Updated notes'],$userIds['administrator']);
 p2_check($pdo->query('SELECT notes FROM establishments WHERE id='.$est1)->fetchColumn()==='Updated notes','Establishment edit works');
 phase2_set_establishment_active($est1,false,$userIds['administrator']);p2_check(!(bool)$pdo->query('SELECT is_active FROM establishments WHERE id='.$est1)->fetchColumn(),'Establishment deactivation works');phase2_set_establishment_active($est1,true,$userIds['administrator']);
 $estIds[]=$est2=phase2_create_establishment(['registration_code'=>$prefix.'-E2','business_name'=>'Second fictional business','owner_name'=>'Second Owner','address'=>'Second fictional address','registration_date'=>'2026-09-27'],$userIds['administrator']);
 $trapInput=['establishment_id'=>$est1,'trap_code'=>$prefix.'-T1','name'=>'Primary test trap','capacity_liters'=>'60','low_threshold'=>'20','medium_threshold'=>'50','high_threshold'=>'75','critical_threshold'=>'90','installation_date'=>'2026-09-27','last_service_date'=>''];
 $trapIds[]=$trap1=phase2_create_trap($trapInput,$userIds['administrator']);p2_check((int)$pdo->query('SELECT establishment_id FROM grease_traps WHERE id='.$trap1)->fetchColumn()===$est1,'Grease trap creation works');
 $invalid=$trapInput;$invalid['low_threshold']='70';$invalid['medium_threshold']='50';p2_expect_validation(fn()=>phase2_create_trap($invalid,$userIds['administrator']),'Thresholds must follow low < medium < high < critical, between 0 and 100.','Invalid threshold order is rejected');
 $trapInput['establishment_id']=$est2;$trapInput['trap_code']=$prefix.'-T2';$trapInput['name']='Second test trap';$trapIds[]=$trap2=phase2_create_trap($trapInput,$userIds['administrator']);
 $deviceInput=['device_code'=>$prefix.'-D1','name'=>'Phase 2 ESP32','device_type'=>'ESP32 DevKit','firmware_version'=>'test','installation_date'=>'2026-09-27','establishment_id'=>$est1,'grease_trap_id'=>$trap1];
 $deviceIds[]=$device1=phase2_create_device($deviceInput,$userIds['administrator']);p2_check((int)$pdo->query('SELECT grease_trap_id FROM device_assignments WHERE device_id='.$device1.' AND ended_at IS NULL')->fetchColumn()===$trap1,'Device registration and assignment work');
 $cross=$deviceInput;$cross['establishment_id']=$est1;$cross['grease_trap_id']=$trap2;p2_expect_validation(fn()=>phase2_update_device($device1,$cross,$userIds['administrator']),'The selected grease trap does not belong to the selected establishment.','Cross-establishment assignment is rejected');
 $deviceInput['establishment_id']=$est2;$deviceInput['grease_trap_id']=$trap2;$deviceInput['name']='Updated Phase 2 ESP32';phase2_update_device($device1,$deviceInput,$userIds['administrator']);p2_check((int)$pdo->query('SELECT grease_trap_id FROM device_assignments WHERE device_id='.$device1.' AND ended_at IS NULL')->fetchColumn()===$trap2,'Device edit changes assignment and preserves history');
 $movedTrap=$trapInput;$movedTrap['establishment_id']=$est1;p2_expect_validation(fn()=>phase2_update_trap($trap2,$movedTrap,$userIds['administrator']),'A grease trap with device assignment history cannot be moved to another establishment.','Trap assignment history cannot be moved across establishments');
 phase2_set_device_active($device1,false,$userIds['administrator']);p2_check(!(bool)$pdo->query('SELECT is_active FROM devices WHERE id='.$device1)->fetchColumn(),'Device deactivation works');phase2_set_device_active($device1,true,$userIds['administrator']);
 $admin=p2_client();p2_login($admin,$emails[0],$password);$dashboard=p2_request($admin,'/admin/dashboard.php');p2_check($dashboard['status']===200&&str_contains($dashboard['body'],'Administrative dashboard'),'Authenticated dashboard loads');
 $moduleResponses=[p2_request($admin,'/admin/grease-traps.php'),p2_request($admin,'/admin/grease-trap-view.php?id='.$trap2),p2_request($admin,'/admin/devices.php'),p2_request($admin,'/admin/device-view.php?id='.$device1)];p2_check(count(array_filter($moduleResponses,fn($response)=>$response['status']===200))===4,'Authenticated grease-trap and device pages load');
 $detail=p2_request($admin,'/admin/establishment-view.php?id='.$est1);p2_check(str_contains($detail['body'],'&lt;script&gt;alert(1)&lt;/script&gt;')&&!str_contains($detail['body'],'<script>alert(1)</script>'),'Stored HTML is escaped in Phase 2 details');
 $list=p2_request($admin,'/admin/establishments.php');$before=(int)$pdo->query("SELECT COUNT(*) FROM establishments WHERE registration_code='FORGED-P2'")->fetchColumn();$forged=p2_request($admin,'/admin/establishments.php',['csrf_token'=>'forged','action'=>'create','registration_code'=>'FORGED-P2','business_name'=>'Forged','owner_name'=>'Forged','address'=>'Forged','registration_date'=>'2026-09-27']);$after=(int)$pdo->query("SELECT COUNT(*) FROM establishments WHERE registration_code='FORGED-P2'")->fetchColumn();p2_check($forged['status']===403&&$before===$after,'Phase 2 CSRF validation blocks writes');
 $staff=p2_client();p2_login($staff,$emails[1],$password);$staffList=p2_request($staff,'/admin/establishments.php');p2_check($staffList['status']===200&&!str_contains($staffList['body'],'Add establishment'),'Environmental staff receive read-only Phase 2 access');$staffPost=p2_request($staff,'/admin/establishments.php',['csrf_token'=>p2_token($staffList),'action'=>'create']);p2_check($staffPost['status']===403,'Environmental staff write attempt is explicitly forbidden');
 $auditCount=(int)$pdo->query("SELECT COUNT(*) FROM audit_logs WHERE user_id=".$userIds['administrator']." AND action IN ('ESTABLISHMENT_CREATED','ESTABLISHMENT_UPDATED','ESTABLISHMENT_DEACTIVATED','GREASE_TRAP_CREATED','DEVICE_REGISTERED','DEVICE_UPDATED','DEVICE_ASSIGNMENT_CHANGED')")->fetchColumn();p2_check($auditCount>=7,'Important Phase 2 changes are audited');
 echo PHP_EOL.$checks." Phase 2 checks passed.\n";
}finally{
 foreach($deviceIds as $id){$pdo->prepare('DELETE FROM device_assignments WHERE device_id=?')->execute([$id]);$pdo->prepare('DELETE FROM devices WHERE id=?')->execute([$id]);}
 foreach($trapIds as $id)$pdo->prepare('DELETE FROM grease_traps WHERE id=?')->execute([$id]);
 foreach($estIds as $id)$pdo->prepare('DELETE FROM establishments WHERE id=?')->execute([$id]);
 foreach($userIds as $id){$pdo->prepare('DELETE FROM audit_logs WHERE user_id=?')->execute([$id]);$pdo->prepare('DELETE FROM users WHERE id=?')->execute([$id]);}
 foreach($emails as $email)$pdo->prepare('DELETE FROM login_attempts WHERE email_hash=?')->execute([hash('sha256',strtolower($email))]);
}
