<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'||!in_array('--allow-local-fixtures',$argv,true))exit("Usage: php tests/phase3.php --allow-local-fixtures\n");
require dirname(__DIR__).'/includes/bootstrap.php';require_once dirname(__DIR__).'/includes/telemetry.php';require_once dirname(__DIR__).'/includes/monitoring.php';
if($config['environment']!=='development')throw new RuntimeException('Development fixtures only.');
$base=rtrim((string)$config['test_base_url'],'/');$checks=0;$ids=['users'=>[],'establishments'=>[],'traps'=>[],'devices'=>[],'assignments'=>[]];$emails=[];$password='Phase3!'.bin2hex(random_bytes(10));
function p3_check(bool $ok,string $label):void{global $checks;if(!$ok)throw new RuntimeException('FAIL: '.$label);$checks++;echo 'PASS: '.$label.PHP_EOL;}
function p3_client():CurlHandle{$c=curl_init();curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_COOKIEFILE=>'',CURLOPT_TIMEOUT=>15]);return$c;}
function p3_request(CurlHandle $c,string $path,string $method='GET',?string $body=null,array $headers=[]):array{global$base;curl_setopt_array($c,[CURLOPT_URL=>$base.$path,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_POSTFIELDS=>$body,CURLOPT_HTTPHEADER=>$headers]);$raw=curl_exec($c);if($raw===false)throw new RuntimeException(curl_error($c));$size=curl_getinfo($c,CURLINFO_HEADER_SIZE);$content=substr($raw,$size);return['status'=>curl_getinfo($c,CURLINFO_RESPONSE_CODE),'headers'=>substr($raw,0,$size),'body'=>$content,'json'=>json_decode($content,true)];}
function p3_api(array|string $body,?string $key=null):array{$headers=['Content-Type: application/json','Accept: application/json'];if($key!==null)$headers[]='X-Device-Key: '.$key;return p3_request(p3_client(),'/api/device/telemetry.php','POST',is_string($body)?$body:json_encode($body),$headers);}
function p3_token(array $response):string{preg_match('/name="csrf_token" value="([a-f0-9]{64})"/',$response['body'],$m);if(!isset($m[1]))throw new RuntimeException('Missing CSRF token.');return$m[1];}
function p3_login(CurlHandle $c,string $email,string $password):void{$form=p3_request($c,'/public/login.php');$reply=p3_request($c,'/public/login.php','POST',http_build_query(['csrf_token'=>p3_token($form),'email'=>$email,'password'=>$password]),['Content-Type: application/x-www-form-urlencoded']);p3_check($reply['status']===303,'Phase 3 test user authenticated');}
try{
 $pdo=db();p3_check(version_compare(APP_VERSION,'0.5.0','>='),'Application retains Phase 3 or newer version');$columns=$pdo->query('SHOW COLUMNS FROM sensor_readings')->fetchAll(PDO::FETCH_COLUMN);p3_check(!array_diff(['reading_uuid','sequence_number','received_at','device_reported_percent'],$columns),'Phase 3 telemetry migration is applied');
 $roles=$pdo->query('SELECT slug,id FROM roles')->fetchAll(PDO::FETCH_KEY_PAIR);foreach(['administrator','environmental_staff'] as $role){$email='phase3-'.$role.'-'.bin2hex(random_bytes(4)).'@example.test';$emails[]=$email;$q=$pdo->prepare('INSERT INTO users(role_id,full_name,email,password_hash)VALUES(?,?,?,?)');$q->execute([$roles[$role],'Phase 3 '.$role,$email,password_hash($password,PASSWORD_DEFAULT)]);$ids['users'][$role]=(int)$pdo->lastInsertId();}
 $prefix='P3'.strtoupper(bin2hex(random_bytes(3)));$q=$pdo->prepare('INSERT INTO establishments(registration_code,business_name,owner_name,address,registration_date,created_by)VALUES(?,?,?,?,CURRENT_DATE(),?)');$q->execute([$prefix.'E','Phase 3 fictional site','Test Owner','Test Address',$ids['users']['administrator']]);$site=(int)$pdo->lastInsertId();$ids['establishments'][]=$site;
 foreach([1,2]as$n){$q=$pdo->prepare('INSERT INTO grease_traps(establishment_id,trap_code,name,capacity_liters,low_threshold,medium_threshold,high_threshold,critical_threshold,empty_distance_cm,full_distance_cm)VALUES(?,?,?,60,20,50,75,90,30,5)');$q->execute([$site,$prefix.'T'.$n,'Phase 3 Trap '.$n]);$ids['traps'][]=(int)$pdo->lastInsertId();}
 $key=bin2hex(random_bytes(32));$q=$pdo->prepare('INSERT INTO devices(device_code,name,device_type,api_key_hash)VALUES(?,?,?,?)');$q->execute([$prefix.'D','Phase 3 ESP32','ESP32 DevKit',hash('sha256',$key)]);$device=(int)$pdo->lastInsertId();$ids['devices'][]=$device;$pdo->prepare('INSERT INTO device_assignments(device_id,grease_trap_id,started_at)VALUES(?,?,UTC_TIMESTAMP())')->execute([$device,$ids['traps'][0]]);$assignment=(int)$pdo->lastInsertId();$ids['assignments'][]=$assignment;
 $uuid='123e4567-e89b-42d3-a456-426614174000';$body=['device_id'=>$prefix.'D','grease_trap_id'=>$ids['traps'][0],'ultrasonic_distance'=>12.4,'waste_level_percent'=>58,'reading_uuid'=>$uuid,'temperature'=>31.5,'turbidity'=>250,'flow_rate'=>1.8,'gas_value'=>120];
 p3_check(p3_api($body)['status']===401,'Missing device key rejected');p3_check(p3_api($body,str_repeat('a',64))['status']===401,'Invalid device key rejected');$unknown=$body;$unknown['device_id']='UNKNOWN-P3';p3_check(p3_api($unknown,$key)['status']===404,'Unknown device rejected');
 $pdo->prepare('UPDATE devices SET is_active=0 WHERE id=?')->execute([$device]);p3_check(p3_api($body,$key)['status']===403,'Inactive device rejected');$pdo->prepare('UPDATE devices SET is_active=1 WHERE id=?')->execute([$device]);
 $wrong=$body;$wrong['grease_trap_id']=$ids['traps'][1];p3_check(p3_api($wrong,$key)['status']===403,'Wrong grease trap assignment rejected');p3_check(p3_api('{',$key)['status']===400,'Invalid JSON rejected');$invalid=$body;$invalid['ultrasonic_distance']=-1;p3_check(p3_api($invalid,$key)['status']===422,'Negative distance rejected');$invalid=$body;$invalid['waste_level_percent']=-1;p3_check(p3_api($invalid,$key)['status']===422,'Fill percentage below zero rejected');$invalid['waste_level_percent']=101;p3_check(p3_api($invalid,$key)['status']===422,'Fill percentage above 100 rejected');
 $pdo->prepare('UPDATE grease_traps SET empty_distance_cm=NULL,full_distance_cm=NULL WHERE id=?')->execute([$ids['traps'][0]]);p3_check(p3_api($body,$key)['status']===409,'Missing ultrasonic calibration rejected');$pdo->prepare('UPDATE grease_traps SET empty_distance_cm=30,full_distance_cm=5 WHERE id=?')->execute([$ids['traps'][0]]);
 $reply=p3_api($body,$key);p3_check($reply['status']===201&&$reply['json']['success'],'Valid device telemetry accepted');$readingId=(int)$reply['json']['data']['reading_id'];$row=$pdo->query('SELECT * FROM sensor_readings WHERE id='.$readingId)->fetch();p3_check((float)$row['ultrasonic_distance_cm']===12.4&&(float)$row['waste_level_percent']===70.4&&(float)$row['device_reported_percent']===58.0,'Raw distance and server-derived fill stored');p3_check((float)$row['temperature_c']===31.5&&(float)$row['turbidity_ntu']===250.0&&(float)$row['flow_rate_lpm']===1.8&&(float)$row['gas_value']===120.0,'Optional future sensor fields stored');p3_check($row['received_at']!==null,'Server received timestamp stored');p3_check((bool)$pdo->query('SELECT last_seen_at IS NOT NULL FROM devices WHERE id='.$device)->fetchColumn(),'Device last_seen updated');
 $duplicate=p3_api($body,$key);p3_check($duplicate['status']===200&&!empty($duplicate['json']['data']['duplicate'])&&(int)$pdo->query('SELECT COUNT(*) FROM sensor_readings WHERE device_assignment_id='.$assignment)->fetchColumn()===1,'Idempotent retry does not duplicate telemetry');$conflict=$body;$conflict['ultrasonic_distance']=13.4;p3_check(p3_api($conflict,$key)['status']===409,'Idempotency key reuse with different telemetry rejected');
 p3_check(p3_request(p3_client(),'/api/admin/monitoring.php')['status']===401,'Admin monitoring API requires authentication');
 $admin=p3_client();p3_login($admin,$emails[0],$password);$latest=p3_request($admin,'/api/admin/monitoring.php');p3_check($latest['status']===200&&array_filter($latest['json']['data']['traps'],fn($trap)=>$trap['reading_id']===$readingId),'Latest monitoring endpoint returns stored reading');$history=p3_request($admin,'/api/admin/history.php?grease_trap_id='.$ids['traps'][0].'&range=24h');p3_check($history['status']===200&&(int)($history['json']['data']['total']??-1)===1&&(int)($history['json']['data']['readings'][0]['id']??0)===$readingId,'Historical endpoint returns correct trap readings');$monitorPage=p3_request($admin,'/admin/monitoring.php?trap_id='.$ids['traps'][0].'&range=24h');p3_check($monitorPage['status']===200&&str_contains($monitorPage['body'],'Waste level history')&&str_contains($monitorPage['body'],'70.4%'),'Monitoring page and chart use stored telemetry');
 p3_check(!phase3_simulator_available('production'),'Simulator is unavailable in production mode');$pdo->prepare('UPDATE devices SET last_seen_at=NULL WHERE id=?')->execute([$device]);$simForm=p3_request($admin,'/admin/telemetry-simulator.php');$simReply=p3_request($admin,'/admin/telemetry-simulator.php','POST',http_build_query(['csrf_token'=>p3_token($simForm),'device_id'=>$device,'grease_trap_id'=>$ids['traps'][0],'device_key'=>$key,'ultrasonic_distance'=>'11.25']),['Content-Type: application/x-www-form-urlencoded']);p3_check($simReply['status']===200&&(int)$pdo->query('SELECT COUNT(*) FROM sensor_readings WHERE device_assignment_id='.$assignment.' AND is_simulated=1')->fetchColumn()===1,'Development simulator uses the real telemetry API');
 $devicePage=p3_request($admin,'/admin/device-view.php?id='.$device);$rotate=p3_request($admin,'/admin/devices.php','POST',http_build_query(['csrf_token'=>p3_token($devicePage),'action'=>'credential','id'=>$device]),['Content-Type: application/x-www-form-urlencoded']);$credentialPage=p3_request($admin,'/admin/device-view.php?id='.$device);preg_match('/<code>([a-f0-9]{64})<\/code>/',$credentialPage['body'],$credentialMatch);$newKey=$credentialMatch[1]??'';p3_check($rotate['status']===303&&strlen($newKey)===64&&hash_equals((string)$pdo->query('SELECT api_key_hash FROM devices WHERE id='.$device)->fetchColumn(),hash('sha256',$newKey)),'Administrator can generate and rotate a hashed device credential');$hiddenAgain=p3_request($admin,'/admin/device-view.php?id='.$device);p3_check(!str_contains($hiddenAgain['body'],$newKey)&&p3_api($body,$key)['status']===401,'Plaintext credential is shown once and the previous key is revoked');
 $staff=p3_client();p3_login($staff,$emails[1],$password);p3_check(p3_request($staff,'/admin/telemetry-simulator.php')['status']===303,'Environmental staff cannot access simulator');p3_check((int)$pdo->query("SELECT COUNT(*) FROM audit_logs WHERE user_id=".$ids['users']['administrator']." AND action='TELEMETRY_SIMULATED'")->fetchColumn()===1,'Simulator use is audited without logging its key');
 echo PHP_EOL.$checks." Phase 3 checks passed.\n";
}finally{
 foreach($ids['devices'] as$id){$pdo->prepare('DELETE FROM alerts WHERE device_assignment_id IN(SELECT id FROM device_assignments WHERE device_id=?)')->execute([$id]);$pdo->prepare('DELETE FROM sensor_readings WHERE device_assignment_id IN(SELECT id FROM device_assignments WHERE device_id=?)')->execute([$id]);$pdo->prepare('DELETE FROM device_assignments WHERE device_id=?')->execute([$id]);$pdo->prepare('DELETE FROM devices WHERE id=?')->execute([$id]);}
 foreach($ids['traps'] as$id)$pdo->prepare('DELETE FROM grease_traps WHERE id=?')->execute([$id]);foreach($ids['establishments']as$id)$pdo->prepare('DELETE FROM establishments WHERE id=?')->execute([$id]);foreach($ids['users']as$id){$pdo->prepare('DELETE FROM audit_logs WHERE user_id=?')->execute([$id]);$pdo->prepare('DELETE FROM users WHERE id=?')->execute([$id]);}foreach($emails as$email)$pdo->prepare('DELETE FROM login_attempts WHERE email_hash=?')->execute([hash('sha256',strtolower($email))]);
}
