<?php
declare(strict_types=1);
require dirname(__DIR__).'/includes/bootstrap.php';require_once dirname(__DIR__).'/includes/alert-engine.php';$user=require_staff();$pdo=db();$defs=phase4_alert_definitions();
$where=[];$params=[];foreach(['status','severity','alert_type'] as $field){$value=trim((string)($_GET[$field]??''));if($value!==''){$where[]='al.'.$field.'=?';$params[]=$value;}}
foreach(['establishment_id'=>'e.id','device_id'=>'d.id'] as $key=>$column){$value=filter_input(INPUT_GET,$key,FILTER_VALIDATE_INT);if($value){$where[]=$column.'=?';$params[]=$value;}}
if(($from=(string)($_GET['from']??''))!==''&&preg_match('/^\d{4}-\d{2}-\d{2}$/D',$from)){$where[]='al.first_triggered_at>=?';$params[]=$from.' 00:00:00';}if(($to=(string)($_GET['to']??''))!==''&&preg_match('/^\d{4}-\d{2}-\d{2}$/D',$to)){$where[]='al.first_triggered_at<?';$params[]=(new DateTimeImmutable($to))->modify('+1 day')->format('Y-m-d').' 00:00:00';}
$sql="SELECT al.*,e.business_name,g.name trap_name,d.device_code,ua.full_name acknowledged_name,ur.full_name resolved_name FROM alerts al JOIN device_assignments a ON a.id=al.device_assignment_id JOIN devices d ON d.id=a.device_id JOIN grease_traps g ON g.id=a.grease_trap_id JOIN establishments e ON e.id=g.establishment_id LEFT JOIN users ua ON ua.id=al.acknowledged_by LEFT JOIN users ur ON ur.id=al.resolved_by".($where?' WHERE '.implode(' AND ',$where):'')." ORDER BY (al.status='RESOLVED'),al.last_triggered_at DESC LIMIT 250";$q=$pdo->prepare($sql);$q->execute($params);$alerts=$q->fetchAll();$sites=$pdo->query('SELECT id,business_name FROM establishments ORDER BY business_name')->fetchAll();$devices=$pdo->query('SELECT id,device_code FROM devices ORDER BY device_code')->fetchAll();$pageTitle='Alerts';$activeNav='alerts';require dirname(__DIR__).'/includes/header.php';
?>
<div class="page-heading"><div><div class="breadcrumb">Operations <span>/</span> Alerts</div><h1>Alert management</h1><p>Active, acknowledged, and resolved operational alerts.</p></div></div>
<form class="panel alert-filters" method="get"><label>Status<select name="status"><option value="">All</option><?php foreach(['ACTIVE','ACKNOWLEDGED','RESOLVED'] as $v): ?><option<?= selected($_GET['status']??'',$v) ?>><?= e($v) ?></option><?php endforeach; ?></select></label><label>Severity<select name="severity"><option value="">All</option><?php foreach(['INFO','WARNING','CRITICAL'] as $v): ?><option<?= selected($_GET['severity']??'',$v) ?>><?= e($v) ?></option><?php endforeach; ?></select></label><label>Type<select name="alert_type"><option value="">All</option><?php foreach($defs as $type=>$def): ?><option value="<?= e($type) ?>"<?= selected($_GET['alert_type']??'',$type) ?>><?= e($def['label']) ?></option><?php endforeach; ?></select></label><label>Establishment<select name="establishment_id"><option value="">All</option><?php foreach($sites as $site): ?><option value="<?= (int)$site['id'] ?>"<?= selected($_GET['establishment_id']??'',(string)$site['id']) ?>><?= e($site['business_name']) ?></option><?php endforeach; ?></select></label><label>Device<select name="device_id"><option value="">All</option><?php foreach($devices as $device): ?><option value="<?= (int)$device['id'] ?>"<?= selected($_GET['device_id']??'',(string)$device['id']) ?>><?= e($device['device_code']) ?></option><?php endforeach; ?></select></label><label>From<input type="date" name="from" value="<?= e($from) ?>"></label><label>To<input type="date" name="to" value="<?= e($to) ?>"></label><button class="button button-secondary" type="submit">Filter</button></form>
<section class="panel section-panel"><div class="table-scroll"><table><thead><tr><th>Alert</th><th>Severity</th><th>Establishment / trap</th><th>Device</th><th>Latest value</th><th>First / last trigger</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($alerts as $alert): ?><tr><td><strong><?= e(phase4_alert_label($alert['alert_type'])) ?></strong><br><span class="muted"><?= e($alert['message']) ?></span></td><td><span class="status-badge status-<?= e(strtolower($alert['severity'])) ?>"><?= e($alert['severity']) ?></span></td><td><?= e($alert['business_name']) ?><br><span class="muted"><?= e($alert['trap_name']) ?></span></td><td><?= e($alert['device_code']) ?></td><td><?= $alert['sensor_value']===null?'Not applicable':e((string)$alert['sensor_value']) ?></td><td><?= e(display_date($alert['first_triggered_at'])) ?><br><span class="muted"><?= e(display_date($alert['last_triggered_at'])) ?> · <?= (int)$alert['trigger_count'] ?>×</span></td><td><span class="status-badge status-<?= e(strtolower($alert['status'])) ?>"><?= e($alert['status']) ?></span></td><td><a class="table-action" href="<?= e(url('admin/alert-view.php?id='.(int)$alert['id'])) ?>">View</a></td></tr><?php endforeach; ?><?php if(!$alerts): ?><tr><td colspan="8" class="empty-state">No alerts match these filters.</td></tr><?php endif; ?></tbody></table></div></section>
<?php require dirname(__DIR__).'/includes/footer.php'; ?>
