<?php
declare(strict_types=1);
require dirname(__DIR__).'/includes/bootstrap.php';require_once dirname(__DIR__).'/includes/alert-engine.php';$user=require_staff();$id=query_id('id');if(!$id){http_response_code(404);exit('Alert not found.');}$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){if($user['role_slug']!=='administrator'){http_response_code(403);$errors[]='Administrator access is required for alert actions.';}elseif(!valid_csrf()){http_response_code(403);$errors[]='The form expired. Reload and try again.';}else try{if(($_POST['action']??'')==='acknowledge')phase4_acknowledge_alert($id,(int)$user['id']);elseif(($_POST['action']??'')==='resolve')phase4_resolve_alert($id,(int)$user['id'],(string)($_POST['resolution_note']??''));else throw new InvalidArgumentException('Unsupported action.');set_flash('success','Alert status updated.');redirect('admin/alert-view.php?id='.$id);}catch(InvalidArgumentException $e){$errors[]=$e->getMessage();}}
$q=db()->prepare("SELECT al.*,e.business_name,g.id trap_id,g.name trap_name,d.id device_id,d.device_code,ua.full_name acknowledged_name,ur.full_name resolved_name FROM alerts al JOIN device_assignments a ON a.id=al.device_assignment_id JOIN devices d ON d.id=a.device_id JOIN grease_traps g ON g.id=a.grease_trap_id JOIN establishments e ON e.id=g.establishment_id LEFT JOIN users ua ON ua.id=al.acknowledged_by LEFT JOIN users ur ON ur.id=al.resolved_by WHERE al.id=?");$q->execute([$id]);$alert=$q->fetch();if(!$alert){http_response_code(404);exit('Alert not found.');}$readings=db()->prepare('SELECT * FROM sensor_readings WHERE device_assignment_id=? ORDER BY recorded_at DESC,id DESC LIMIT 10');$readings->execute([$alert['device_assignment_id']]);$readings=$readings->fetchAll();$pageTitle=phase4_alert_label($alert['alert_type']);$activeNav='alerts';$flash=consume_flash();require dirname(__DIR__).'/includes/header.php';
?>
<div class="page-heading"><div><div class="breadcrumb"><a href="<?= e(url('admin/alerts.php')) ?>">Alerts</a> <span>/</span> Details</div><h1><?= e(phase4_alert_label($alert['alert_type'])) ?></h1><p><?= e($alert['message']) ?></p></div><span class="status-badge status-<?= e(strtolower($alert['status'])) ?>"><?= e($alert['status']) ?></span></div><?php if($flash): ?><div class="notice notice-<?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?><?php foreach($errors as $error): ?><div class="notice notice-error"><?= e($error) ?></div><?php endforeach; ?>
<section class="detail-grid"><article class="panel detail-card"><h2>Alert information</h2><dl class="detail-list"><div><dt>Severity</dt><dd><?= e($alert['severity']) ?></dd></div><div><dt>Sensor</dt><dd><?= e($alert['sensor_name']??'Device heartbeat') ?></dd></div><div><dt>Latest value</dt><dd><?= $alert['sensor_value']===null?'Not applicable':e((string)$alert['sensor_value']) ?></dd></div><div><dt>Threshold</dt><dd><?= $alert['threshold_value']===null?'Not applicable':e((string)$alert['threshold_value']) ?></dd></div><div><dt>First triggered</dt><dd><?= e(display_date($alert['first_triggered_at'])) ?></dd></div><div><dt>Last triggered</dt><dd><?= e(display_date($alert['last_triggered_at'])) ?></dd></div><div><dt>Trigger count</dt><dd><?= (int)$alert['trigger_count'] ?></dd></div></dl></article><article class="panel detail-card"><h2>Location and action history</h2><dl class="detail-list"><div><dt>Establishment</dt><dd><?= e($alert['business_name']) ?></dd></div><div><dt>Grease trap</dt><dd><a href="<?= e(url('admin/grease-trap-view.php?id='.(int)$alert['trap_id'])) ?>"><?= e($alert['trap_name']) ?></a></dd></div><div><dt>Device</dt><dd><a href="<?= e(url('admin/device-view.php?id='.(int)$alert['device_id'])) ?>"><?= e($alert['device_code']) ?></a></dd></div><div><dt>Acknowledged by</dt><dd><?= e($alert['acknowledged_name']??'Not acknowledged') ?></dd></div><div><dt>Resolved by</dt><dd><?= e($alert['resolved_name']??($alert['resolved_at']?'Automatic recovery':'Not resolved')) ?></dd></div><div><dt>Resolution</dt><dd><?= e($alert['resolution_note']??'—') ?></dd></div></dl></article></section>
<?php if($user['role_slug']==='administrator'&&$alert['status']!=='RESOLVED'): ?><section class="panel record-form"><div class="form-actions"><?php if($alert['status']==='ACTIVE'): ?><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="acknowledge"><button class="button button-secondary" type="submit">Acknowledge</button></form><?php endif; ?><form method="post" class="inline-resolution"><?= csrf_field() ?><input type="hidden" name="action" value="resolve"><input type="text" name="resolution_note" maxlength="1000" placeholder="Optional resolution note"><button class="button button-primary" type="submit">Resolve alert</button></form></div></section><?php endif; ?>
<section class="panel section-panel"><div class="panel-heading"><h2>Related recent telemetry</h2></div><div class="table-scroll"><table><thead><tr><th>Recorded</th><th>Level</th><th>Distance</th><th>Temperature</th><th>Turbidity</th><th>Flow</th></tr></thead><tbody><?php foreach($readings as $r): ?><tr><td><?= e(display_date($r['recorded_at'])) ?></td><td><?= e($r['waste_level_percent'].'%') ?></td><td><?= e((string)($r['ultrasonic_distance_cm']??'—')) ?></td><td><?= e((string)($r['temperature_c']??'—')) ?></td><td><?= e((string)($r['turbidity_ntu']??'—')) ?></td><td><?= e((string)($r['flow_rate_lpm']??'—')) ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php require dirname(__DIR__).'/includes/footer.php'; ?>
