<?php
declare(strict_types=1);
require dirname(__DIR__).'/includes/bootstrap.php';require_once dirname(__DIR__).'/includes/admin-core.php';
$user=require_staff();$canManage=$user['role_slug']==='administrator';$pageTitle='Devices';$activeNav='devices';$pageScript='assets/js/admin-forms.js';$errors=[];$action=$_GET['action']??'list';$editId=query_id();
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!$canManage){http_response_code(403);$errors[]='Only Barangay Administrators can change device records.';}
 elseif(!valid_csrf()){http_response_code(403);$errors[]='The form expired. Reload and try again.';}
 else try{$post=post_string('action');$id=post_id('id');
  if($post==='create'){$id=phase2_create_device($_POST,(int)$user['id']);flash('success','Device registered.');redirect('admin/device-view.php?id='.$id);}
  if($post==='update'&&$id){phase2_update_device($id,$_POST,(int)$user['id']);flash('success','Device and assignment updated.');redirect('admin/device-view.php?id='.$id);}
  if($post==='status'&&$id){phase2_set_device_active($id,post_string('active')==='1',(int)$user['id']);flash('success','Device status updated.');redirect('admin/device-view.php?id='.$id);}
  throw new Phase2ValidationException(['Invalid device action.']);
 }catch(Phase2ValidationException $error){$errors=$error->errors;$action=post_string('action')==='create'?'add':(post_string('action')==='update'?'edit':'list');$editId=post_id('id');}
}
$establishments=db()->query('SELECT id,business_name FROM establishments WHERE is_active=1 ORDER BY business_name')->fetchAll();
$traps=db()->query("SELECT g.id,g.establishment_id,g.name,g.trap_code,a.device_id FROM grease_traps g LEFT JOIN device_assignments a ON a.grease_trap_id=g.id AND a.ended_at IS NULL WHERE g.is_active=1 ORDER BY g.name")->fetchAll();
$form=['device_code'=>'','name'=>'','device_type'=>'ESP32 DevKit','firmware_version'=>'','installation_date'=>'','establishment_id'=>'','grease_trap_id'=>''];
if($action==='edit'&&$editId){$q=db()->prepare("SELECT d.*,g.establishment_id,a.grease_trap_id FROM devices d LEFT JOIN device_assignments a ON a.device_id=d.id AND a.ended_at IS NULL LEFT JOIN grease_traps g ON g.id=a.grease_trap_id WHERE d.id=?");$q->execute([$editId]);$record=$q->fetch();if(!$record){http_response_code(404);$errors[]='Device was not found.';$action='list';}else$form=array_replace($form,$record);}
if($errors&&in_array($action,['add','edit'],true))foreach($form as $key=>$value)if(isset($_POST[$key])&&is_string($_POST[$key]))$form[$key]=trim($_POST[$key]);
$freshness=(int)db()->query("SELECT setting_value FROM system_settings WHERE setting_key='device_offline_timeout_minutes'")->fetchColumn()*60;
$search=trim((string)($_GET['search']??''));$status=$_GET['status']??'all';if(!in_array($status,['all','active','inactive','assigned','unassigned'],true))$status='all';$where=[];$params=[];
if($search!==''){$where[]='(d.device_code LIKE ? OR d.name LIKE ? OR d.device_type LIKE ? OR e.business_name LIKE ?)';$term='%'.$search.'%';array_push($params,$term,$term,$term,$term);}if($status==='active')$where[]='d.is_active=1';elseif($status==='inactive')$where[]='d.is_active=0';elseif($status==='assigned')$where[]='a.id IS NOT NULL';elseif($status==='unassigned')$where[]='a.id IS NULL';$whereSql=$where?'WHERE '.implode(' AND ',$where):'';
$q=db()->prepare("SELECT d.*,a.grease_trap_id,g.name trap_name,e.id establishment_id,e.business_name FROM devices d LEFT JOIN device_assignments a ON a.device_id=d.id AND a.ended_at IS NULL LEFT JOIN grease_traps g ON g.id=a.grease_trap_id LEFT JOIN establishments e ON e.id=g.establishment_id $whereSql ORDER BY d.device_code");$q->execute($params);$rows=$q->fetchAll();$flash=consume_flash();require dirname(__DIR__).'/includes/header.php';
?>
<div class="page-heading"><div><div class="breadcrumb">Operations <span>/</span> Devices</div><h1><?= $action==='add'?'Register device':($action==='edit'?'Edit device':'Devices') ?></h1><p>Register human-readable device codes and maintain consistent grease-trap assignments.</p></div><?php if($canManage&&$action==='list'): ?><a class="button button-primary" href="<?= e(url('admin/devices.php?action=add')) ?>"><?= icon('plus') ?> Register device</a><?php endif; ?></div>
<?php if($flash): ?><div class="notice notice-<?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?><?php if($errors): ?><div class="notice notice-error" role="alert"><strong>Check the form:</strong><ul><?php foreach($errors as $error): ?><li><?= e($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<?php if(in_array($action,['add','edit'],true)&&$canManage): ?><form class="panel record-form" method="post" data-device-form novalidate><?= csrf_field() ?><input type="hidden" name="action" value="<?= $action==='add'?'create':'update' ?>"><?php if($editId): ?><input type="hidden" name="id" value="<?= $editId ?>"><?php endif; ?><div class="panel-heading"><div><h2>Device information</h2><p>API credentials are provisioned separately and are never displayed here.</p></div></div><div class="form-grid">
<?php foreach([['device_code','Device code','text'],['name','Device name','text'],['device_type','Device type','text'],['firmware_version','Firmware version','text'],['installation_date','Installation date','date']] as [$name,$label,$type]): ?><label class="form-field"><span><?= e($label) ?><?= in_array($name,['device_code','name','device_type'])?' *':'' ?></span><input type="<?= e($type) ?>" name="<?= e($name) ?>" value="<?= e((string)$form[$name]) ?>"></label><?php endforeach; ?>
<label class="form-field"><span>Establishment assignment</span><select name="establishment_id" data-establishment-select><option value="">Leave unassigned</option><?php foreach($establishments as $est): ?><option value="<?= (int)$est['id'] ?>"<?= selected($form['establishment_id'],$est['id']) ?>><?= e($est['business_name']) ?></option><?php endforeach; ?></select></label>
<label class="form-field"><span>Grease trap assignment</span><select name="grease_trap_id" data-trap-select><option value="">Leave unassigned</option><?php foreach($traps as $trap): $unavailable=$trap['device_id']!==null&&(int)$trap['device_id']!==$editId; ?><option value="<?= (int)$trap['id'] ?>" data-establishment="<?= (int)$trap['establishment_id'] ?>"<?= selected($form['grease_trap_id'],$trap['id']) ?><?= $unavailable?' disabled':'' ?>><?= e($trap['name'].' · '.$trap['trap_code'].($unavailable?' (Assigned)':'')) ?></option><?php endforeach; ?></select></label>
</div><div class="threshold-help">The selected grease trap must belong to the selected establishment. Assignment history is retained when this changes.</div><div class="form-actions"><a class="button button-secondary" href="<?= e(url('admin/devices.php')) ?>">Cancel</a><button class="button button-primary" type="submit">Save device</button></div></form>
<?php else: ?><form class="filter-bar" method="get"><input type="search" name="search" value="<?= e($search) ?>" placeholder="Search device, type, or establishment"><select name="status"><option value="all">All records</option><option value="active"<?= selected($status,'active') ?>>Active</option><option value="inactive"<?= selected($status,'inactive') ?>>Inactive</option><option value="assigned"<?= selected($status,'assigned') ?>>Assigned</option><option value="unassigned"<?= selected($status,'unassigned') ?>>Unassigned</option></select><button class="button button-secondary" type="submit"><?= icon('search') ?> Search</button></form><section class="panel section-panel"><div class="table-scroll"><table><thead><tr><th>Device</th><th>Type</th><th>Establishment</th><th>Grease trap</th><th>Firmware</th><th>Connection state</th><th>Last seen</th><th>Action</th></tr></thead><tbody><?php foreach($rows as $row): $state=phase2_device_status($row,$freshness); ?><tr><td><strong><?= e($row['device_code']) ?></strong><br><span class="muted"><?= e($row['name']) ?></span></td><td><?= e($row['device_type']) ?></td><td><?= e($row['business_name']??'Not assigned') ?></td><td><?= e($row['trap_name']??'Not assigned') ?></td><td><?= e($row['firmware_version']??'Unknown') ?></td><td><span class="status-badge status-<?= e(strtolower(str_replace(' ','-',$state))) ?>"><?= e($state) ?></span></td><td><?= $row['last_seen_at']?e(display_date($row['last_seen_at'])):'Awaiting telemetry' ?></td><td><a class="table-action" href="<?= e(url('admin/device-view.php?id='.(int)$row['id'])) ?>">View</a><?php if($canManage): ?> <a class="table-action" href="<?= e(url('admin/devices.php?action=edit&id='.(int)$row['id'])) ?>">Edit</a><?php endif; ?></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="8" class="empty-state">No devices match the current filters.</td></tr><?php endif; ?></tbody></table></div></section><?php endif; ?>
<?php require dirname(__DIR__).'/includes/footer.php'; ?>
