<?php
declare(strict_types=1);
require dirname(__DIR__).'/includes/bootstrap.php';require_once dirname(__DIR__).'/includes/admin-core.php';require_once dirname(__DIR__).'/includes/alert-engine.php';$user=require_staff();$canManage=$user['role_slug']==='administrator';$id=query_id();
$q=db()->prepare("SELECT d.*,a.id assignment_id,a.started_at,g.id trap_id,g.name trap_name,e.id establishment_id,e.business_name FROM devices d LEFT JOIN device_assignments a ON a.device_id=d.id AND a.ended_at IS NULL LEFT JOIN grease_traps g ON g.id=a.grease_trap_id LEFT JOIN establishments e ON e.id=g.establishment_id WHERE d.id=?");$q->execute([$id]);$device=$q->fetch();if(!$device)redirect('admin/devices.php');
$q=db()->prepare("SELECT a.started_at,a.ended_at,g.name trap_name,e.business_name FROM device_assignments a JOIN grease_traps g ON g.id=a.grease_trap_id JOIN establishments e ON e.id=g.establishment_id WHERE a.device_id=? ORDER BY a.started_at DESC,a.id DESC");$q->execute([$id]);$history=$q->fetchAll();
$q=db()->prepare('SELECT COUNT(*) FROM sensor_readings r JOIN device_assignments a ON a.id=r.device_assignment_id WHERE a.device_id=?');$q->execute([$id]);$readingCount=(int)$q->fetchColumn();
$q=db()->prepare('SELECT r.* FROM sensor_readings r JOIN device_assignments a ON a.id=r.device_assignment_id WHERE a.device_id=? ORDER BY r.recorded_at DESC,r.id DESC LIMIT 1');$q->execute([$id]);$latestReading=$q->fetch();
$q=db()->prepare("SELECT al.id,al.alert_type,al.severity,al.status,al.last_triggered_at,g.name trap_name FROM alerts al JOIN device_assignments a ON a.id=al.device_assignment_id JOIN grease_traps g ON g.id=a.grease_trap_id WHERE a.device_id=? ORDER BY (al.status='RESOLVED'),al.last_triggered_at DESC LIMIT 25");$q->execute([$id]);$alerts=$q->fetchAll();
$credentialOnce=$_SESSION['device_credential_once']??null;if(!is_array($credentialOnce)||(int)($credentialOnce['device_id']??0)!==$id)$credentialOnce=null;unset($_SESSION['device_credential_once']);
$freshness=(int)db()->query("SELECT setting_value FROM system_settings WHERE setting_key='device_offline_timeout_minutes'")->fetchColumn()*60;$state=phase2_device_status($device,$freshness);$pageTitle=$device['device_code'];$activeNav='devices';$flash=consume_flash();require dirname(__DIR__).'/includes/header.php';
?>
<div class="page-heading"><div><div class="breadcrumb"><a href="<?= e(url('admin/devices.php')) ?>">Devices</a> <span>/</span> Details</div><h1><?= e($device['device_code']) ?></h1><p><?= e($device['name']) ?></p></div><div class="heading-actions"><?php if($canManage): ?><a class="button button-secondary" href="<?= e(url('admin/devices.php?action=edit&id='.$id)) ?>"><?= icon('edit') ?> Edit assignment</a><form method="post" action="<?= e(url('admin/devices.php')) ?>" data-confirm="<?= $device['api_key_hash']?'Rotate this device credential? The old key will stop working.':'Generate a device credential?' ?>"><?= csrf_field() ?><input type="hidden" name="action" value="credential"><input type="hidden" name="id" value="<?= (int)$id ?>"><button class="button button-secondary" type="submit"><?= $device['api_key_hash']?'Rotate credential':'Generate credential' ?></button></form><form method="post" action="<?= e(url('admin/devices.php')) ?>" data-confirm="<?= $device['is_active']?'Deactivate this device?':'Activate this device?' ?>"><?= csrf_field() ?><input type="hidden" name="action" value="status"><input type="hidden" name="id" value="<?= (int)$id ?>"><input type="hidden" name="active" value="<?= $device['is_active']?'0':'1' ?>"><button class="button <?= $device['is_active']?'button-danger':'button-primary' ?>" type="submit"><?= $device['is_active']?'Deactivate':'Activate' ?></button></form><?php endif; ?></div></div>
<?php if($flash): ?><div class="notice notice-<?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?>
<?php if($credentialOnce): ?><div class="notice notice-success credential-once"><strong>One-time device credential</strong><code><?= e($credentialOnce['key']) ?></code><p>Save this in the ESP32 private configuration. AQUASENSE+ stores only its SHA-256 hash.</p></div><?php endif; ?>
<section class="detail-grid"><article class="panel detail-card"><div class="panel-heading"><h2>Device information</h2><span class="status-badge status-<?= e(strtolower(str_replace(' ','-',$state))) ?>"><?= e($state) ?></span></div><dl class="detail-list"><div><dt>Device code</dt><dd><?= e($device['device_code']) ?></dd></div><div><dt>Type</dt><dd><?= e($device['device_type']) ?></dd></div><div><dt>Firmware</dt><dd><?= e($device['firmware_version']??'Unknown') ?></dd></div><div><dt>Installation date</dt><dd><?= e($device['installation_date']??'Not recorded') ?></dd></div><div><dt>Last seen</dt><dd><?= $device['last_seen_at']?e(display_date($device['last_seen_at'])):'Not connected yet' ?></dd></div><div><dt>Reading count</dt><dd><?= $readingCount ?></dd></div><div><dt>API credential</dt><dd><?= $device['api_key_hash']?'Configured (hidden)':'Not generated' ?></dd></div><div><dt>Registered</dt><dd><?= e(display_date($device['created_at'])) ?></dd></div></dl></article><article class="panel detail-card"><div class="panel-heading"><h2>Current assignment</h2></div><?php if($device['assignment_id']): ?><dl class="detail-list"><div><dt>Establishment</dt><dd><a href="<?= e(url('admin/establishment-view.php?id='.(int)$device['establishment_id'])) ?>"><?= e($device['business_name']) ?></a></dd></div><div><dt>Grease trap</dt><dd><a href="<?= e(url('admin/grease-trap-view.php?id='.(int)$device['trap_id'])) ?>"><?= e($device['trap_name']) ?></a></dd></div><div><dt>Assigned</dt><dd><?= e(display_date($device['started_at'])) ?></dd></div><div><dt>Latest reading</dt><dd><?= $latestReading?e(number_format((float)$latestReading['waste_level_percent'],1).'% · '.number_format((float)$latestReading['ultrasonic_distance_cm'],2).' cm · '.$latestReading['level_status']):'Awaiting sensor telemetry.' ?></dd></div></dl><?php else: ?><p class="empty-state">Not assigned. Choose an establishment and grease trap when editing this device.</p><?php endif; ?></article></section>
<section class="panel section-panel"><div class="panel-heading"><div><h2>Assignment history</h2><p>Previous assignments remain available for accountability.</p></div></div><div class="table-scroll"><table><thead><tr><th>Establishment</th><th>Grease trap</th><th>Started</th><th>Ended</th></tr></thead><tbody><?php foreach($history as $row): ?><tr><td><?= e($row['business_name']) ?></td><td><?= e($row['trap_name']) ?></td><td><?= e(display_date($row['started_at'])) ?></td><td><?= $row['ended_at']?e(display_date($row['ended_at'])):'Current' ?></td></tr><?php endforeach; ?><?php if(!$history): ?><tr><td colspan="4" class="empty-state">No assignment history yet.</td></tr><?php endif; ?></tbody></table></div></section>
<section class="panel section-panel"><div class="panel-heading"><div><h2>Device alert history</h2><p>Includes active conditions, offline alerts, and resolved history.</p></div></div><div class="table-scroll"><table><thead><tr><th>Alert</th><th>Grease trap</th><th>Severity</th><th>Status</th><th>Last triggered</th><th>Action</th></tr></thead><tbody><?php foreach($alerts as $alert): ?><tr><td><?= e(phase4_alert_label($alert['alert_type'])) ?></td><td><?= e($alert['trap_name']) ?></td><td><?= e($alert['severity']) ?></td><td><?= e($alert['status']) ?></td><td><?= e(display_date($alert['last_triggered_at'])) ?></td><td><a class="table-action" href="<?= e(url('admin/alert-view.php?id='.(int)$alert['id'])) ?>">View</a></td></tr><?php endforeach; ?><?php if(!$alerts): ?><tr><td colspan="6" class="empty-state">No alerts have been recorded.</td></tr><?php endif; ?></tbody></table></div></section>
<?php require dirname(__DIR__).'/includes/footer.php'; ?>
