<?php
declare(strict_types=1);
require dirname(__DIR__).'/includes/bootstrap.php';require_once dirname(__DIR__).'/includes/admin-core.php';
$user=require_staff();$canManage=$user['role_slug']==='administrator';$id=query_id();if(!$id){http_response_code(404);redirect('admin/establishments.php');}
$q=db()->prepare('SELECT * FROM establishments WHERE id=?');$q->execute([$id]);$est=$q->fetch();if(!$est){http_response_code(404);redirect('admin/establishments.php');}
$q=db()->prepare("SELECT g.*,d.id device_id,d.device_code,d.name device_name,d.firmware_version,d.last_seen_at,d.is_active device_active,
 r.waste_level_percent,r.temperature_c,r.recorded_at FROM grease_traps g
 LEFT JOIN device_assignments a ON a.grease_trap_id=g.id AND a.ended_at IS NULL LEFT JOIN devices d ON d.id=a.device_id
 LEFT JOIN sensor_readings r ON r.id=(SELECT sr.id FROM sensor_readings sr WHERE sr.device_assignment_id=a.id ORDER BY sr.recorded_at DESC,sr.id DESC LIMIT 1)
 WHERE g.establishment_id=? ORDER BY g.name");$q->execute([$id]);$traps=$q->fetchAll();
$freshness=(int)db()->query("SELECT setting_value FROM system_settings WHERE setting_key='device_offline_timeout_minutes'")->fetchColumn()*60;
$q=db()->prepare('SELECT * FROM oil_surrenders WHERE establishment_id=? ORDER BY surrendered_at DESC LIMIT 10');$q->execute([$id]);$surrenders=$q->fetchAll();
$q=db()->prepare("SELECT it.*,os.transaction_code FROM incentive_transactions it JOIN oil_surrenders os ON os.id=it.oil_surrender_id WHERE os.establishment_id=? ORDER BY it.created_at DESC LIMIT 10");$q->execute([$id]);$incentives=$q->fetchAll();
$pageTitle=$est['business_name'];$activeNav='establishments';$flash=consume_flash();require dirname(__DIR__).'/includes/header.php';
?>
<div class="page-heading"><div><div class="breadcrumb"><a href="<?= e(url('admin/establishments.php')) ?>">Establishments</a> <span>/</span> Details</div><h1><?= e($est['business_name']) ?></h1><p><?= e($est['registration_code']) ?></p></div><div class="heading-actions"><?php if($canManage): ?><a class="button button-secondary" href="<?= e(url('admin/establishments.php?action=edit&id='.$id)) ?>"><?= icon('edit') ?> Edit</a><form method="post" action="<?= e(url('admin/establishments.php')) ?>" data-confirm="<?= $est['is_active']?'Deactivate this establishment?':'Activate this establishment?' ?>"><?= csrf_field() ?><input type="hidden" name="action" value="status"><input type="hidden" name="id" value="<?= $id ?>"><input type="hidden" name="active" value="<?= $est['is_active']?'0':'1' ?>"><button class="button <?= $est['is_active']?'button-danger':'button-primary' ?>" type="submit"><?= $est['is_active']?'Deactivate':'Activate' ?></button></form><?php endif; ?></div></div>
<?php if($flash): ?><div class="notice notice-<?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?>
<section class="detail-grid"><article class="panel detail-card"><div class="panel-heading"><h2>Establishment information</h2><span class="status-badge status-<?= $est['is_active']?'active':'inactive' ?>"><?= $est['is_active']?'ACTIVE':'INACTIVE' ?></span></div><dl class="detail-list"><div><dt>Owner</dt><dd><?= e($est['owner_name']) ?></dd></div><div><dt>Address</dt><dd><?= e($est['address']) ?></dd></div><div><dt>Contact</dt><dd><?= e($est['contact_number']??'Not provided') ?></dd></div><div><dt>Email</dt><dd><?= e($est['email']??'Not provided') ?></dd></div><div><dt>Registration date</dt><dd><?= e(date('F j, Y',strtotime($est['registration_date']))) ?></dd></div><div><dt>Notes</dt><dd><?= e($est['notes']??'No notes') ?></dd></div></dl></article>
<article class="panel detail-card"><div class="panel-heading"><h2>Monitoring</h2></div><div class="empty-content"><?= icon('activity') ?><p><?= $traps&&array_filter($traps,fn($t)=>$t['recorded_at'])?'Latest telemetry appears with each grease trap below.':'Monitoring data will appear after sensor integration.' ?></p></div></article></section>
<section class="panel section-panel"><div class="panel-heading"><div><h2>Grease traps and devices</h2><p>Registered equipment assigned to this establishment.</p></div><?php if($canManage): ?><a class="button button-secondary button-small" href="<?= e(url('admin/grease-traps.php?action=add&establishment_id='.$id)) ?>">Add grease trap</a><?php endif; ?></div><div class="table-scroll"><table><thead><tr><th>Grease trap</th><th>Capacity</th><th>Status</th><th>Assigned device</th><th>Firmware</th><th>Connection</th><th>Last seen</th><th>Latest level</th><th>Latest temperature</th><th>Action</th></tr></thead><tbody><?php foreach($traps as $trap): $deviceState=$trap['device_id']?phase2_device_status(['is_active'=>$trap['device_active'],'last_seen_at'=>$trap['last_seen_at']],$freshness):'NOT CONNECTED'; ?><tr><td><?= e($trap['name']) ?><br><span class="muted"><?= e($trap['trap_code']) ?></span></td><td><?= e(number_format((float)$trap['capacity_liters'],1)) ?> L</td><td><?= $trap['is_active']?'Active':'Inactive' ?></td><td><?= e($trap['device_code']??'Awaiting device') ?><?php if($trap['device_name']): ?><br><span class="muted"><?= e($trap['device_name']) ?></span><?php endif; ?></td><td><?= e($trap['firmware_version']??'Unknown') ?></td><td><span class="status-badge status-<?= e(strtolower(str_replace(' ','-',$deviceState))) ?>"><?= e($deviceState) ?></span></td><td><?= $trap['last_seen_at']?e(display_date($trap['last_seen_at'])):'Awaiting telemetry' ?></td><td><?= $trap['waste_level_percent']===null?'No data yet':e($trap['waste_level_percent'].'%') ?></td><td><?= $trap['temperature_c']===null?'No data yet':e($trap['temperature_c'].' °C') ?></td><td><a class="table-action" href="<?= e(url('admin/grease-trap-view.php?id='.(int)$trap['id'])) ?>">View</a></td></tr><?php endforeach; ?><?php if(!$traps): ?><tr><td colspan="10" class="empty-state">No grease traps are registered for this establishment.</td></tr><?php endif; ?></tbody></table></div></section>
<div class="detail-grid"><section class="panel section-panel"><div class="panel-heading"><h2>Oil surrenders</h2></div><?php if(!$surrenders): ?><p class="empty-state">No oil surrender records yet.</p><?php else: ?><div class="table-scroll"><table><thead><tr><th>Transaction</th><th>Quantity</th><th>Status</th></tr></thead><tbody><?php foreach($surrenders as $row): ?><tr><td><?= e($row['transaction_code']) ?></td><td><?= e($row['oil_quantity'].' '.$row['oil_unit']) ?></td><td><?= e($row['status']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section><section class="panel section-panel"><div class="panel-heading"><h2>Incentives</h2></div><?php if(!$incentives): ?><p class="empty-state">No incentive records yet.</p><?php else: ?><div class="table-scroll"><table><thead><tr><th>Surrender</th><th>Rice</th><th>Status</th></tr></thead><tbody><?php foreach($incentives as $row): ?><tr><td><?= e($row['transaction_code']) ?></td><td><?= e($row['rice_quantity'].' '.$row['rice_unit']) ?></td><td><?= e($row['status']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section></div>
<?php require dirname(__DIR__).'/includes/footer.php'; ?>
