<?php
declare(strict_types=1);
require dirname(__DIR__).'/includes/bootstrap.php';require_once dirname(__DIR__).'/includes/admin-core.php';
$user=require_staff();$canManage=$user['role_slug']==='administrator';$pageTitle='Grease Traps';$activeNav='grease-traps';$errors=[];$action=$_GET['action']??'list';$editId=query_id();
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!$canManage){http_response_code(403);$errors[]='Only Barangay Administrators can change grease trap records.';}
 elseif(!valid_csrf()){http_response_code(403);$errors[]='The form expired. Reload and try again.';}
 else try{$post=post_string('action');$id=post_id('id');
  if($post==='create'){$id=phase2_create_trap($_POST,(int)$user['id']);flash('success','Grease trap registered.');redirect('admin/grease-trap-view.php?id='.$id);}
  if($post==='update'&&$id){phase2_update_trap($id,$_POST,(int)$user['id']);flash('success','Grease trap updated.');redirect('admin/grease-trap-view.php?id='.$id);}
  if($post==='status'&&$id){phase2_set_trap_active($id,post_string('active')==='1',(int)$user['id']);flash('success','Grease trap status updated.');redirect('admin/grease-trap-view.php?id='.$id);}
  throw new Phase2ValidationException(['Invalid grease trap action.']);
 }catch(Phase2ValidationException $error){$errors=$error->errors;$action=post_string('action')==='create'?'add':(post_string('action')==='update'?'edit':'list');$editId=post_id('id');}
}
$establishments=db()->query('SELECT id,business_name,is_active FROM establishments ORDER BY business_name')->fetchAll();
$form=['establishment_id'=>(int)($_GET['establishment_id']??0),'trap_code'=>'','name'=>'','capacity_liters'=>'','low_threshold'=>'20','medium_threshold'=>'50','high_threshold'=>'75','critical_threshold'=>'90','installation_date'=>'','last_service_date'=>''];
if($action==='edit'&&$editId){$q=db()->prepare('SELECT * FROM grease_traps WHERE id=?');$q->execute([$editId]);$record=$q->fetch();if(!$record){http_response_code(404);$errors[]='Grease trap was not found.';$action='list';}else$form=array_replace($form,$record);}
if($errors&&in_array($action,['add','edit'],true))foreach($form as $key=>$value)if(isset($_POST[$key])&&is_string($_POST[$key]))$form[$key]=trim($_POST[$key]);
$search=trim((string)($_GET['search']??''));$status=$_GET['status']??'all';if(!in_array($status,['all','active','inactive','unassigned','awaiting_telemetry'],true))$status='all';$where=[];$params=[];
if($search!==''){$where[]='(g.name LIKE ? OR g.trap_code LIKE ? OR e.business_name LIKE ?)';$term='%'.$search.'%';array_push($params,$term,$term,$term);}if($status==='active')$where[]='g.is_active=1';elseif($status==='inactive')$where[]='g.is_active=0';elseif($status==='unassigned')$where[]='d.id IS NULL';elseif($status==='awaiting_telemetry')$where[]='d.id IS NOT NULL AND r.id IS NULL';$whereSql=$where?'WHERE '.implode(' AND ',$where):'';
$q=db()->prepare("SELECT g.*,e.business_name,d.id device_id,d.device_code,d.last_seen_at,r.recorded_at latest_recorded_at FROM grease_traps g JOIN establishments e ON e.id=g.establishment_id LEFT JOIN device_assignments a ON a.grease_trap_id=g.id AND a.ended_at IS NULL LEFT JOIN devices d ON d.id=a.device_id LEFT JOIN sensor_readings r ON r.id=(SELECT sr.id FROM sensor_readings sr WHERE sr.device_assignment_id=a.id ORDER BY sr.recorded_at DESC,sr.id DESC LIMIT 1) $whereSql ORDER BY e.business_name,g.name");$q->execute($params);$rows=$q->fetchAll();$flash=consume_flash();require dirname(__DIR__).'/includes/header.php';
?>
<div class="page-heading"><div><div class="breadcrumb">Operations <span>/</span> Grease traps</div><h1><?= $action==='add'?'Register grease trap':($action==='edit'?'Edit grease trap':'Grease traps') ?></h1><p>Configure capacity, calibration thresholds, and establishment ownership.</p></div><?php if($canManage&&$action==='list'): ?><a class="button button-primary" href="<?= e(url('admin/grease-traps.php?action=add')) ?>"><?= icon('plus') ?> Add grease trap</a><?php endif; ?></div>
<?php if($flash): ?><div class="notice notice-<?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?><?php if($errors): ?><div class="notice notice-error" role="alert"><strong>Check the form:</strong><ul><?php foreach($errors as $error): ?><li><?= e($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<?php if(in_array($action,['add','edit'],true)&&$canManage): ?><form class="panel record-form" method="post" novalidate><?= csrf_field() ?><input type="hidden" name="action" value="<?= $action==='add'?'create':'update' ?>"><?php if($editId): ?><input type="hidden" name="id" value="<?= $editId ?>"><?php endif; ?><div class="panel-heading"><div><h2>Grease trap information</h2><p>Capacity is stored in liters. Thresholds are percentages.</p></div></div><div class="form-grid">
<label class="form-field"><span>Establishment *</span><select name="establishment_id" required><option value="">Select establishment</option><?php foreach($establishments as $est): ?><option value="<?= (int)$est['id'] ?>"<?= selected($form['establishment_id'],$est['id']) ?>><?= e($est['business_name'].($est['is_active']?'':' (Inactive)')) ?></option><?php endforeach; ?></select></label>
<?php foreach([['trap_code','Trap code','text'],['name','Trap name / label','text'],['capacity_liters','Capacity (liters)','number'],['low_threshold','Low threshold (%)','number'],['medium_threshold','Medium threshold (%)','number'],['high_threshold','High threshold (%)','number'],['critical_threshold','Critical threshold (%)','number'],['installation_date','Installation date','date'],['last_service_date','Last service date','date']] as [$name,$label,$type]): ?><label class="form-field"><span><?= e($label) ?><?= in_array($name,['trap_code','name','capacity_liters','low_threshold','medium_threshold','high_threshold','critical_threshold'])?' *':'' ?></span><input type="<?= e($type) ?>" name="<?= e($name) ?>" value="<?= e((string)$form[$name]) ?>"<?= $type==='number'?' step="0.01"':'' ?>></label><?php endforeach; ?>
</div><div class="threshold-help">Required order: low &lt; medium &lt; high &lt; critical, all between 0% and 100%.</div><div class="form-actions"><a class="button button-secondary" href="<?= e(url('admin/grease-traps.php')) ?>">Cancel</a><button class="button button-primary" type="submit">Save grease trap</button></div></form>
<?php else: ?><form class="filter-bar" method="get"><input type="search" name="search" value="<?= e($search) ?>" placeholder="Search trap, code, or establishment"><select name="status"><option value="all">All statuses</option><option value="active"<?= selected($status,'active') ?>>Active</option><option value="inactive"<?= selected($status,'inactive') ?>>Inactive</option><option value="unassigned"<?= selected($status,'unassigned') ?>>Awaiting device</option><option value="awaiting_telemetry"<?= selected($status,'awaiting_telemetry') ?>>Awaiting telemetry</option></select><button class="button button-secondary" type="submit"><?= icon('search') ?> Search</button></form><section class="panel section-panel"><div class="table-scroll"><table><thead><tr><th>Trap</th><th>Establishment</th><th>Capacity</th><th>Thresholds L / M / H / C</th><th>Assigned device</th><th>Operational status</th><th>Action</th></tr></thead><tbody><?php foreach($rows as $row): $operationalStatus=!(bool)$row['is_active']?'INACTIVE':(!$row['device_id']?'AWAITING DEVICE':(!$row['latest_recorded_at']?'AWAITING TELEMETRY':'ACTIVE')); ?><tr><td><strong><?= e($row['name']) ?></strong><br><span class="muted"><?= e($row['trap_code']) ?></span></td><td><?= e($row['business_name']) ?></td><td><?= e(number_format((float)$row['capacity_liters'],1)) ?> L</td><td><?= e(implode(' / ',[$row['low_threshold'],$row['medium_threshold'],$row['high_threshold'],$row['critical_threshold']])) ?>%</td><td><?= e($row['device_code']??'Awaiting device') ?></td><td><span class="status-badge status-<?= e(strtolower(str_replace(' ','-',$operationalStatus))) ?>"><?= e($operationalStatus) ?></span></td><td><a class="table-action" href="<?= e(url('admin/grease-trap-view.php?id='.(int)$row['id'])) ?>">View</a><?php if($canManage): ?> <a class="table-action" href="<?= e(url('admin/grease-traps.php?action=edit&id='.(int)$row['id'])) ?>">Edit</a><?php endif; ?></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="7" class="empty-state">No grease traps match the current filters.</td></tr><?php endif; ?></tbody></table></div></section><?php endif; ?>
<?php require dirname(__DIR__).'/includes/footer.php'; ?>
