<?php
declare(strict_types=1);
require dirname(__DIR__).'/includes/bootstrap.php';require_once dirname(__DIR__).'/includes/admin-core.php';$user=require_staff();$canManage=$user['role_slug']==='administrator';$id=query_id();
$q=db()->prepare("SELECT g.*,e.business_name,e.id establishment_id,d.id device_id,d.device_code,d.name device_name,d.firmware_version,d.last_seen_at,d.is_active device_active,a.id assignment_id FROM grease_traps g JOIN establishments e ON e.id=g.establishment_id LEFT JOIN device_assignments a ON a.grease_trap_id=g.id AND a.ended_at IS NULL LEFT JOIN devices d ON d.id=a.device_id WHERE g.id=?");$q->execute([$id]);$trap=$q->fetch();if(!$trap)redirect('admin/grease-traps.php');
$readings=[];if($trap['assignment_id']){$q=db()->prepare('SELECT * FROM sensor_readings WHERE device_assignment_id=? ORDER BY recorded_at DESC,id DESC LIMIT 10');$q->execute([$trap['assignment_id']]);$readings=$q->fetchAll();}
$pageTitle=$trap['name'];$activeNav='grease-traps';$flash=consume_flash();require dirname(__DIR__).'/includes/header.php';
?>
<div class="page-heading"><div><div class="breadcrumb"><a href="<?= e(url('admin/grease-traps.php')) ?>">Grease traps</a> <span>/</span> Details</div><h1><?= e($trap['name']) ?></h1><p><?= e($trap['business_name'].' · '.$trap['trap_code']) ?></p></div><div class="heading-actions"><?php if($canManage): ?><a class="button button-secondary" href="<?= e(url('admin/grease-traps.php?action=edit&id='.$id)) ?>"><?= icon('edit') ?> Edit</a><form method="post" action="<?= e(url('admin/grease-traps.php')) ?>" data-confirm="<?= $trap['is_active']?'Deactivate this grease trap?':'Activate this grease trap?' ?>"><?= csrf_field() ?><input type="hidden" name="action" value="status"><input type="hidden" name="id" value="<?= (int)$id ?>"><input type="hidden" name="active" value="<?= $trap['is_active']?'0':'1' ?>"><button class="button <?= $trap['is_active']?'button-danger':'button-primary' ?>" type="submit"><?= $trap['is_active']?'Deactivate':'Activate' ?></button></form><?php endif; ?></div></div>
<?php if($flash): ?><div class="notice notice-<?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?>
<section class="detail-grid"><article class="panel detail-card"><div class="panel-heading"><h2>Configuration</h2><span class="status-badge status-<?= $trap['is_active']?'active':'inactive' ?>"><?= $trap['is_active']?'ACTIVE':'INACTIVE' ?></span></div><dl class="detail-list"><div><dt>Establishment</dt><dd><a href="<?= e(url('admin/establishment-view.php?id='.(int)$trap['establishment_id'])) ?>"><?= e($trap['business_name']) ?></a></dd></div><div><dt>Capacity</dt><dd><?= e(number_format((float)$trap['capacity_liters'],2)) ?> L</dd></div><div><dt>Thresholds</dt><dd><?= e("Low {$trap['low_threshold']}% · Medium {$trap['medium_threshold']}% · High {$trap['high_threshold']}% · Critical {$trap['critical_threshold']}%") ?></dd></div><div><dt>Installation</dt><dd><?= e($trap['installation_date']??'Not recorded') ?></dd></div><div><dt>Last service</dt><dd><?= e($trap['last_service_date']??'Not recorded') ?></dd></div></dl></article><article class="panel detail-card"><div class="panel-heading"><h2>Assigned device</h2></div><?php if($trap['device_id']): ?><dl class="detail-list"><div><dt>Device</dt><dd><a href="<?= e(url('admin/device-view.php?id='.(int)$trap['device_id'])) ?>"><?= e($trap['device_code']) ?></a></dd></div><div><dt>Name</dt><dd><?= e($trap['device_name']) ?></dd></div><div><dt>Firmware</dt><dd><?= e($trap['firmware_version']??'Unknown') ?></dd></div><div><dt>Last seen</dt><dd><?= $trap['last_seen_at']?e(display_date($trap['last_seen_at'])):'Not connected yet' ?></dd></div></dl><?php else: ?><p class="empty-state">No device is assigned. Assign one from Device Management.</p><?php endif; ?></article></section>
<section class="panel section-panel"><div class="panel-heading"><div><h2>Basic monitoring history</h2><p>Latest existing records only. Full telemetry history is Phase 3.</p></div></div><div class="table-scroll"><table><thead><tr><th>Recorded</th><th>Waste level</th><th>Distance</th><th>Temperature</th><th>Status</th><th>Source</th></tr></thead><tbody><?php foreach($readings as $reading): ?><tr><td><?= e(display_date($reading['recorded_at'])) ?></td><td><?= e($reading['waste_level_percent'].'%') ?></td><td><?= $reading['ultrasonic_distance_cm']===null?'No data':e($reading['ultrasonic_distance_cm'].' cm') ?></td><td><?= $reading['temperature_c']===null?'No data':e($reading['temperature_c'].' °C') ?></td><td><?= e($reading['level_status']) ?></td><td><?= $reading['is_simulated']?'Development sample':(!empty($reading['is_test'])?'Ultrasonic test':'Device') ?></td></tr><?php endforeach; ?><?php if(!$readings): ?><tr><td colspan="6" class="empty-state">Monitoring data will appear after sensor integration.</td></tr><?php endif; ?></tbody></table></div></section>
<?php require dirname(__DIR__).'/includes/footer.php'; ?>
