<?php
declare(strict_types=1);
require dirname(__DIR__).'/includes/bootstrap.php';
require_once dirname(__DIR__).'/includes/monitoring.php';
$user=require_staff();$pageTitle='Monitoring';$activeNav='monitoring';$pageScript='assets/js/monitoring.js';
$latest=phase3_monitoring_latest();$trapId=query_id('trap_id');$range=(string)($_GET['range']??'today');$from=isset($_GET['from'])?(string)$_GET['from']:null;$to=isset($_GET['to'])?(string)$_GET['to']:null;$history=null;$errors=[];
if($trapId){try{$history=phase3_monitoring_history($trapId,$range,$from,$to,max(1,(int)($_GET['page']??1)));}catch(InvalidArgumentException $error){$errors[]=$error->getMessage();}}
$chart=[];if($history)foreach(array_reverse($history['readings']) as $reading)$chart[]=['time'=>$reading['recorded_at'],'level'=>$reading['waste_level_percent'],'distance'=>$reading['ultrasonic_distance_cm']];$hasDistance=(bool)array_filter($chart,fn($point)=>$point['distance']!==null);
$chartJson=json_encode($chart,JSON_THROW_ON_ERROR);require dirname(__DIR__).'/includes/header.php';
?>
<div class="page-heading"><div><div class="breadcrumb">Operations <span>/</span> Monitoring</div><h1>Sensor monitoring</h1><p>Live database telemetry from assigned devices. This page refreshes every <?= (int)$config['telemetry_poll_seconds'] ?> seconds.</p></div><?php if($config['environment']==='development'&&$user['role_slug']==='administrator'): ?><a class="button button-secondary" href="<?= e(url('admin/telemetry-simulator.php')) ?>">Development simulator</a><?php endif; ?></div>
<?php foreach($errors as $error): ?><div class="notice notice-error"><?= e($error) ?></div><?php endforeach; ?>
<section class="panel section-panel monitoring-root" data-monitoring-endpoint="<?= e(url('api/admin/monitoring.php')) ?>" data-poll-seconds="<?= (int)$config['telemetry_poll_seconds'] ?>">
<div class="panel-heading"><div><h2>Latest readings</h2><p data-monitoring-updated>Generated <?= e(display_date(str_replace('T',' ',substr($latest['generated_at'],0,19)))) ?></p></div><span class="status-badge status-online" data-poll-status>LIVE POLLING</span></div>
<div class="table-scroll"><table><thead><tr><th>Establishment / trap</th><th>Device</th><th>Device status</th><th>Waste level</th><th>Distance</th><th>Temperature</th><th>Turbidity</th><th>Flow rate</th><th>Gas / odor</th><th>Last update</th><th>Sensor state</th><th>Active alerts</th><th>Action</th></tr></thead><tbody>
<?php foreach($latest['traps'] as $trap): ?><tr data-monitoring-trap="<?= (int)$trap['grease_trap_id'] ?>"><td><strong><?= e($trap['business_name']) ?></strong><br><span class="muted"><?= e($trap['grease_trap_name']) ?></span></td><td data-field="device"><?= e($trap['device_code']??'Not assigned') ?></td><td data-field="device_status"><span class="status-badge status-<?= e(strtolower(str_replace(' ','-',$trap['device_status']))) ?>"><?= e($trap['device_status']) ?></span></td><td data-field="waste_level"><?= $trap['waste_level_percent']===null?'Not available':e(number_format($trap['waste_level_percent'],1).'%') ?></td><td data-field="distance"><?= $trap['ultrasonic_distance_cm']===null?'Not available':e(number_format($trap['ultrasonic_distance_cm'],2).' cm') ?></td><td data-field="temperature"><?= $trap['temperature_c']===null?'Not connected':e(number_format($trap['temperature_c'],1).' °C') ?></td><td data-field="turbidity"><?= $trap['turbidity_ntu']===null?'Not connected':e(number_format($trap['turbidity_ntu'],1).' NTU') ?></td><td data-field="flow"><?= $trap['flow_rate_lpm']===null?'Not connected':e(number_format($trap['flow_rate_lpm'],2).' L/min') ?></td><td data-field="gas"><?= $trap['gas_value']===null?'Not connected':e(number_format($trap['gas_value'],1)) ?></td><td data-field="last_update"><?= $trap['recorded_at']?e(display_date($trap['recorded_at'])):'Awaiting telemetry' ?></td><td data-field="sensor_state"><span class="status-badge status-<?= e(strtolower(str_replace(' ','-',$trap['sensor_state']))) ?>"><?= e($trap['sensor_state']) ?></span></td><td data-field="alerts"><?php if($trap['active_alerts']): foreach($trap['active_alerts'] as $alert): ?><span class="alert-chip severity-<?= e(strtolower($alert['severity'])) ?>"><?= e($alert['label']) ?></span><?php endforeach; else: ?>None<?php endif; ?></td><td><a class="table-action" href="?<?= e(http_build_query(['trap_id'=>$trap['grease_trap_id'],'range'=>'24h'])) ?>">Details</a></td></tr><?php endforeach; ?>
<?php if(!$latest['traps']): ?><tr><td colspan="13" class="empty-state">No grease traps are registered for monitoring.</td></tr><?php endif; ?></tbody></table></div></section>
<?php if($history): ?>
<section class="panel section-panel"><div class="panel-heading"><div><h2><?= e($history['trap']['business_name'].' · '.$history['trap']['name']) ?></h2><p>Calibration: <?= $history['trap']['empty_distance_cm']===null?'Not configured':e($history['trap']['empty_distance_cm'].' cm empty · '.$history['trap']['full_distance_cm'].' cm full') ?></p></div><a class="button button-secondary button-small" href="<?= e(url('admin/grease-trap-view.php?id='.(int)$history['trap']['id'])) ?>">Grease trap details</a></div>
<form class="history-filter" method="get"><input type="hidden" name="trap_id" value="<?= (int)$trapId ?>"><label>Period<select name="range"><option value="today"<?= selected($range,'today') ?>>Today</option><option value="24h"<?= selected($range,'24h') ?>>Last 24 hours</option><option value="7d"<?= selected($range,'7d') ?>>Last 7 days</option><option value="30d"<?= selected($range,'30d') ?>>Last 30 days</option><option value="custom"<?= selected($range,'custom') ?>>Custom range</option></select></label><label>From<input type="date" name="from" value="<?= e($from??'') ?>"></label><label>To<input type="date" name="to" value="<?= e($to??'') ?>"></label><button class="button button-secondary" type="submit">Apply</button></form>
<?php if($chart): ?><div class="telemetry-charts" data-history-chart='<?= e($chartJson) ?>'><article><h3>Waste level history</h3><canvas id="level-history-chart" width="700" height="260" aria-label="Waste level history chart"></canvas></article><?php if($hasDistance): ?><article><h3>Ultrasonic distance history</h3><canvas id="distance-history-chart" width="700" height="260" aria-label="Ultrasonic distance history chart"></canvas></article><?php endif; ?></div><?php endif; ?>
<div class="table-scroll"><table><thead><tr><th>Recorded</th><th>Device</th><th>Waste level</th><th>Distance</th><th>Temperature</th><th>Turbidity</th><th>Flow</th><th>Gas</th><th>Status</th><th>Source</th></tr></thead><tbody><?php foreach($history['readings'] as $reading): ?><tr><td><?= e(display_date($reading['recorded_at'])) ?></td><td><?= e($reading['device_code']) ?></td><td><?= e(number_format($reading['waste_level_percent'],1).'%') ?></td><td><?= $reading['ultrasonic_distance_cm']===null?'Not available':e(number_format($reading['ultrasonic_distance_cm'],2).' cm') ?></td><td><?= $reading['temperature_c']===null?'Not available':e(number_format($reading['temperature_c'],1).' °C') ?></td><td><?= $reading['turbidity_ntu']===null?'Not available':e(number_format($reading['turbidity_ntu'],1).' NTU') ?></td><td><?= $reading['flow_rate_lpm']===null?'Not available':e(number_format($reading['flow_rate_lpm'],2).' L/min') ?></td><td><?= $reading['gas_value']===null?'Not available':e(number_format($reading['gas_value'],1)) ?></td><td><?= e($reading['level_status']) ?></td><td><?= $reading['is_simulated']?'Development simulation':($reading['is_test']?'Ultrasonic test':'Device') ?></td></tr><?php endforeach; ?><?php if(!$history['readings']): ?><tr><td colspan="10" class="empty-state">No telemetry exists in this period.</td></tr><?php endif; ?></tbody></table></div>
<?php if($history['pages']>1): ?><nav class="pagination" aria-label="History pages"><?php for($i=1;$i<=$history['pages'];$i++): ?><a class="<?= $i===$history['page']?'current':'' ?>" href="?<?= e(http_build_query(['trap_id'=>$trapId,'range'=>$range,'from'=>$from,'to'=>$to,'page'=>$i])) ?>"><?= $i ?></a><?php endfor; ?></nav><?php endif; ?></section>
<?php endif; ?>
<?php require dirname(__DIR__).'/includes/footer.php'; ?>
