<?php
declare(strict_types=1);
require dirname(__DIR__).'/includes/bootstrap.php';
require_once dirname(__DIR__).'/includes/oil-surrender.php';
$user=require_staff();$canReview=$user['role_slug']==='administrator';$id=query_id();if(!$id)redirect('admin/oil-surrenders.php');
$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!$canReview){http_response_code(403);$errors[]='Administrator access is required to change review status.';}
    elseif(!valid_csrf()){http_response_code(403);$errors[]='The form expired. Reload and try again.';}
    else try{$version=filter_var($_POST['review_version']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>0]]);if($version===false)throw new Phase5ConflictException('Reload this surrender before reviewing it.');phase5_review(db(),$id,post_string('action'),(int)$user['id'],(int)$version,post_string('remarks'));flash('success','Oil surrender review status was updated.');redirect('admin/oil-surrender-view.php?id='.$id);}catch(Phase5ValidationException|Phase5ConflictException $error){$errors[]=$error->getMessage();http_response_code($error instanceof Phase5ConflictException?409:422);}
}
$surrender=phase5_admin_record(db(),$id);if(!$surrender)redirect('admin/oil-surrenders.php');$evidence=phase5_sensor_evidence(db(),$surrender);
$q=db()->prepare("SELECT l.event_type,l.description,l.created_at,u.full_name FROM compliance_ledger l LEFT JOIN users u ON u.id=l.created_by WHERE l.related_record_type='oil_surrenders' AND l.related_record_id=? ORDER BY l.id DESC");$q->execute([$id]);$history=$q->fetchAll();
$q=db()->prepare("SELECT a.action,a.created_at,u.full_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id WHERE a.record_type='oil_surrenders' AND a.record_id=? ORDER BY a.id DESC");$q->execute([$id]);$auditHistory=$q->fetchAll();
$pageTitle=$surrender['transaction_code'];$activeNav='oil-surrenders';$flash=consume_flash();require dirname(__DIR__).'/includes/header.php';
?>
<div class="page-heading"><div><div class="breadcrumb"><a href="<?= e(url('admin/oil-surrenders.php')) ?>">Oil surrenders</a> <span>/</span> Hybrid Verification</div><h1><?= e($surrender['transaction_code']) ?></h1><p>Compare the owner submission, protected photo, and nearby IoT telemetry.</p></div><span class="status-badge status-<?= e(strtolower(str_replace('_','-',$surrender['status']))) ?>"><?= e(str_replace('_',' ',$surrender['status'])) ?></span></div>
<?php if($flash): ?><div class="notice notice-<?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?><?php foreach($errors as $error): ?><div class="notice notice-error"><?= e($error) ?></div><?php endforeach; ?>
<div class="detail-grid"><article class="panel detail-card"><div class="panel-heading"><h2>Submission information</h2></div><dl class="detail-list"><div><dt>Establishment</dt><dd><a href="<?= e(url('admin/establishment-view.php?id='.(int)$surrender['establishment_id'])) ?>"><?= e($surrender['business_name']) ?></a></dd></div><div><dt>Owner</dt><dd><?= e($surrender['owner_name']) ?></dd></div><div><dt>Submitted by</dt><dd><?= e($surrender['submitter_name']) ?></dd></div><div><dt>Quantity</dt><dd><?= e(number_format((float)$surrender['oil_quantity'],3).' '.$surrender['oil_unit']) ?></dd></div><div><dt>Submitted</dt><dd><?= e(display_date($surrender['surrendered_at'])) ?></dd></div><div><dt>Grease trap</dt><dd><?= e($surrender['grease_trap_name']??'Not selected') ?></dd></div><div><dt>Device snapshot</dt><dd><?= e($surrender['device_code']??'No assigned device') ?></dd></div><div><dt>Owner notes</dt><dd><?= e($surrender['notes']??'No notes provided') ?></dd></div></dl></article>
<article class="panel detail-card"><div class="panel-heading"><h2>Photo evidence</h2></div><?php if($surrender['photo_id']): ?><a class="evidence-preview" href="<?= e(url('admin/oil-surrender-photo.php?id='.(int)$surrender['photo_id'])) ?>" target="_blank" rel="noopener"><img src="<?= e(url('admin/oil-surrender-photo.php?id='.(int)$surrender['photo_id'])) ?>" alt="Owner-submitted oil surrender evidence"></a><dl class="detail-list compact"><div><dt>Uploaded</dt><dd><?= e(display_date($surrender['uploaded_at'])) ?></dd></div><div><dt>Format</dt><dd><?= e($surrender['mime_type']) ?></dd></div><div><dt>Size</dt><dd><?= e(number_format((int)$surrender['file_size']/1024,1).' KB') ?></dd></div></dl><?php else: ?><p class="empty-state">No photo evidence is associated with this record.</p><?php endif; ?></article></div>
<section class="panel section-panel"><div class="panel-heading"><div><h2>Sensor evidence</h2><p>Telemetry within <?= (int)$evidence['window_hours'] ?> hours before and after submission. It supports human review and does not prove the claimed oil quantity.</p></div></div><?php if(!$evidence['readings']): ?><p class="empty-state">No relevant sensor telemetry was recorded for this surrender period.</p><?php else: ?><div class="evidence-summary"><div><span>Level before</span><strong><?= $evidence['before']?e(number_format((float)$evidence['before']['waste_level_percent'],1).'%'):'Not available' ?></strong></div><div><span>Level after</span><strong><?= $evidence['after']?e(number_format((float)$evidence['after']['waste_level_percent'],1).'%'):'Not available' ?></strong></div><div><span>Observed change</span><strong><?= $evidence['level_change']===null?'Not available':e(number_format((float)$evidence['level_change'],1).' percentage points') ?></strong></div></div><div class="table-scroll"><table><thead><tr><th>Recorded</th><th>Device</th><th>Waste level</th><th>Distance</th><th>Temperature</th><th>Status</th></tr></thead><tbody><?php foreach($evidence['readings'] as $reading): ?><tr><td><?= e(display_date($reading['recorded_at'])) ?></td><td><?= e($reading['device_code']) ?></td><td><?= e(number_format((float)$reading['waste_level_percent'],1).'%') ?></td><td><?= $reading['ultrasonic_distance_cm']===null?'Not available':e(number_format((float)$reading['ultrasonic_distance_cm'],2).' cm') ?></td><td><?= $reading['temperature_c']===null?'Not available':e(number_format((float)$reading['temperature_c'],1).' °C') ?></td><td><?= e($reading['level_status']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<div class="detail-grid"><section class="panel section-panel"><div class="panel-heading"><div><h2>Barangay review</h2><p>Final decisions remain manual.</p></div></div><dl class="detail-list"><div><dt>Verification</dt><dd><?= e(str_replace('_',' ',$surrender['verification_status'])) ?></dd></div><div><dt>Reviewer</dt><dd><?= e($surrender['reviewer_name']??'Not assigned') ?></dd></div><div><dt>Review started</dt><dd><?= $surrender['review_started_at']?e(display_date($surrender['review_started_at'])):'Not started' ?></dd></div><div><dt>Reviewed</dt><dd><?= $surrender['reviewed_at']?e(display_date($surrender['reviewed_at'])):'Not finalized' ?></dd></div><div><dt>Remarks</dt><dd><?= e($surrender['remarks']??'No review remarks') ?></dd></div></dl><?php if($canReview&&in_array($surrender['status'],['PENDING','UNDER_REVIEW'],true)): ?><form method="post" class="review-form"><?= csrf_field() ?><input type="hidden" name="review_version" value="<?= (int)$surrender['review_version'] ?>"><label class="form-field"><span>Review remarks</span><textarea name="remarks" maxlength="2000" placeholder="Required when rejecting; optional when approving."><?= e($_POST['remarks']??'') ?></textarea></label><div class="form-actions"><?php if($surrender['status']==='PENDING'): ?><button class="button button-secondary" name="action" value="start_review" type="submit">Start review</button><?php endif; ?><button class="button button-primary" name="action" value="approve" type="submit" data-confirm="Approve this oil surrender?">Approve</button><button class="button button-danger" name="action" value="reject" type="submit" data-confirm="Reject this oil surrender?">Reject</button></div></form><?php elseif(!$canReview): ?><p class="muted">Environmental staff have read-only access under the current permission model.</p><?php endif; ?></section>
<section class="panel section-panel"><div class="panel-heading"><h2>Compliance history</h2></div><div class="timeline-list"><?php foreach($history as $event): ?><div class="timeline-item"><strong><?= e(str_replace('_',' ',$event['event_type'])) ?></strong><span><?= e($event['description']) ?></span><small><?= e(display_date($event['created_at'])) ?> · <?= e($event['full_name']??'System') ?></small></div><?php endforeach; ?><?php if(!$history): ?><p class="empty-state">No compliance events are recorded.</p><?php endif; ?></div></section></div>
<section class="panel section-panel"><div class="panel-heading"><div><h2>Audit history</h2><p>Security and workflow actions recorded for this surrender.</p></div></div><div class="timeline-list"><?php foreach($auditHistory as $event): ?><div class="timeline-item"><strong><?= e(str_replace('_',' ',$event['action'])) ?></strong><small><?= e(display_date($event['created_at'])) ?> · <?= e($event['full_name']??'System') ?></small></div><?php endforeach; ?><?php if(!$auditHistory): ?><p class="empty-state">No audit events are recorded.</p><?php endif; ?></div></section>
<?php require dirname(__DIR__).'/includes/footer.php'; ?>
