<?php
declare(strict_types=1);

function phase7_csv_cell(mixed $value): string
{
    if($value===null)return '';$text=(string)$value;
    if(preg_match('/^[\x00-\x20]*[=+\-@]/u',$text))$text="'".$text;
    return $text;
}

function phase7_csv_response(array $data,array $f): never
{
    $filename='aquasense-'.$data['type'].'-'.$f['period']['from'].'-'.$f['period']['to'].'.csv';
    header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$filename.'"');header('X-Content-Type-Options: nosniff');
    $out=fopen('php://output','wb');fwrite($out,"\xEF\xBB\xBF");
    fputcsv($out,['AQUASENSE+',$data['definition']['title']]);fputcsv($out,['Period',$f['period']['label']]);fputcsv($out,['Filters',phase7_filter_summary($f)]);fputcsv($out,[]);fputcsv($out,array_values($data['columns']));
    foreach($data['rows'] as $row){$line=[];foreach(array_keys($data['columns']) as $key)$line[]=phase7_csv_cell($row[$key]??null);fputcsv($out,$line);}
    if($data['truncated'])fputcsv($out,['NOTICE','Export limited to '.count($data['rows']).' rows. Narrow the filters for a complete export.']);
    fclose($out);exit;
}

function phase7_pdf_response(array $data,array $f,array $user): never
{
    $autoload=dirname(__DIR__).'/vendor/autoload.php';if(!is_file($autoload))throw new RuntimeException('PDF support is not installed. Run composer install.');require_once $autoload;
    $esc=static fn(mixed $v):string=>htmlspecialchars((string)($v??''),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
    $summary='';foreach($data['summary'] as $item)$summary.='<div><b>'.$esc($item['value']).'</b><span>'.$esc($item['label']).'</span></div>';
    $head='';foreach($data['columns'] as $label)$head.='<th>'.$esc($label).'</th>';
    $body='';foreach($data['rows'] as $row){$body.='<tr>';foreach(array_keys($data['columns']) as $key)$body.='<td>'.$esc($row[$key]??'').'</td>';$body.='</tr>';}
    if(!$data['rows'])$body='<tr><td colspan="'.count($data['columns']).'">No data matches the selected filters.</td></tr>';
    $notice=$data['truncated']?'<p class="notice">Large report limited to '.count($data['rows']).' rows. Narrow the filters for a complete record.</p>':'';
    $html='<!doctype html><html><head><meta charset="utf-8"><style>@page{margin:48px 28px 42px}body{font-family:DejaVu Sans,sans-serif;color:#193b35;font-size:8px}h1{font-size:18px;margin:0;color:#174d43}.meta{margin:8px 0 14px;color:#5d6f69}.summary{display:flex;gap:8px;margin:12px 0}.summary div{border:1px solid #cfded8;padding:7px;min-width:110px}.summary b,.summary span{display:block}.summary b{font-size:12px}.summary span{color:#65756f;margin-top:3px}table{width:100%;border-collapse:collapse}th{background:#174d43;color:#fff;text-align:left;padding:5px}td{border-bottom:1px solid #dde7e2;padding:5px;vertical-align:top;overflow-wrap:anywhere}.notice{color:#8b4b20}.footer{position:fixed;bottom:-25px;left:0;right:0;text-align:center;color:#788781;font-size:7px}.footer:after{content:"Page " counter(page)} </style></head><body><h1>AQUASENSE+ — '.$esc($data['definition']['title']).'</h1><div class="meta">Period: '.$esc($f['period']['label']).'<br>Generated: '.$esc(date('M j, Y g:i A')).' (Asia/Manila)<br>Generated by: '.$esc($user['full_name']).'<br>Filters: '.$esc(phase7_filter_summary($f)).'</div><div class="summary">'.$summary.'</div>'.$notice.'<table><thead><tr>'.$head.'</tr></thead><tbody>'.$body.'</tbody></table><div class="footer">AQUASENSE+ official report · </div></body></html>';
    $options=new Dompdf\Options();$options->set('isRemoteEnabled',false);$options->set('isPhpEnabled',false);$options->set('defaultFont','DejaVu Sans');$options->setChroot(dirname(__DIR__));
    $dompdf=new Dompdf\Dompdf($options);$dompdf->loadHtml($html,'UTF-8');$dompdf->setPaper('A4','landscape');$dompdf->render();
    phase7_audit_export(db(),$user,'pdf',$f);
    $filename='aquasense-'.$data['type'].'-'.$f['period']['from'].'-'.$f['period']['to'].'.pdf';$dompdf->stream($filename,['Attachment'=>true]);exit;
}
